### ISSUE TITLE
bug: Query crashed during datax importing process

### ISSUE THREAD

**Issue by yufan022** [datafuselabs/databend#10374]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

0.9.58

### What's Wrong?

error log shows `Out of memory (os error 12)`, but the memory usage is not high.

It happend twice:
1.
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/30121694/223038295-ed0a905e-151b-4a7a-9880-1107a6c5fec4.png">
2.
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/30121694/223034720-85ea3b77-3e93-4592-bc0e-70889c03a133.png">

The error log prior to the crash
```
<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 
2023-03-06T04:18:11.113672Z ERROR databend_query::servers::http::middleware: src/query/service/src/servers/http/middleware.rs:196: http request error: query id not found 90be055c-8538-4f3a-aee6-aeffd7a627a5
2023-03-06T04:19:23.953077Z ERROR databend_query::servers::http::middleware: src/query/service/src/servers/http/middleware.rs:196: http request error: query id not found 851a5f7c-e1e0-4caf-b44d-3fa5d8d00d16
2023-03-06T04:21:21.417970Z ERROR common_tracing::panic_hook: src/common/tracing/src/panic_hook.rs:38: panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /workspace/src/common/base/src/runtime/thread.rs:85:18 backtrace=Backtrace [{ fn: "common_tracing::panic_hook::log_panic", file: "/workspace/src/common/tracing/src/panic_hook.rs", line: 35 }, { fn: "common_tracing::panic_hook::set_panic_hook::{{closure}}", file: "/workspace/src/common/tracing/src/panic_hook.rs", line: 30 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs", line: 2032 }, { fn: "std::panicking::rust_panic_with_hook", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 692 }, { fn: "std::panicking::begin_panic_handler::{{closure}}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 579 }, { fn: "std::sys_common::backtrace::__rust_end_short_backtrace", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs", line: 137 }, { fn: "rust_begin_unwind", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 575 }, { fn: "core::panicking::panic_fmt", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panicking.rs", line: 64 }, { fn: "core::result::unwrap_failed", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/result.rs", line: 1790 }, { fn: "core::result::Result<T,E>::unwrap", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/result.rs", line: 1112 }, { fn: "common_base::runtime::thread::Thread::named_spawn", file: "/workspace/src/common/base/src/runtime/thread.rs", line: 77 }, { fn: "databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads", file: "/workspace/src/query/service/src/pipelines/executor/pipeline_executor.rs", line: 293 }, { fn: "databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute", file: "/workspace/src/query/service/src/pipelines/executor/pipeline_executor.rs", line: 186 }, { fn: "databend_query::pipelines::executor::pipeline_pulling_executor::PipelinePullingExecutor::thread_function::{{closure}}", file: "/workspace/src/query/service/src/pipelines/executor/pipeline_pulling_executor.rs", line: 177 }, { fn: "core::ops::function::FnOnce::call_once", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/ops/function.rs", line: 507 }, { fn: "common_base::runtime::thread::Thread::named_spawn::{{closure}}", file: "/workspace/src/common/base/src/runtime/thread.rs", line: 83 }, { fn: "std::sys_common::backtrace::__rust_begin_short_backtrace", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs", line: 121 }, { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/thread/mod.rs", line: 550 }, { fn: "<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: "std::panicking::try::do_call", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 483 }, { fn: "std::panicking::try", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 447 }, { fn: "std::panic::catch_unwind", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panic.rs", line: 137 }, { fn: "std::thread::Builder::spawn_unchecked_::{{closure}}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/thread/mod.rs", line: 549 }, { fn: "core::ops::function::FnOnce::call_once{{vtable.shim}}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/ops/function.rs", line: 507 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs", line: 2000 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs", line: 2000 }, { fn: "std::sys::unix::thread::Thread::new::thread_start", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread.rs", line: 108 }] panic.file="/workspace/src/common/base/src/runtime/thread.rs" panic.line=85 panic.column=18
2023-03-06T04:21:21.420977Z ERROR common_tracing::panic_hook: src/common/tracing/src/panic_hook.rs:38: panicked at 'failed to set up alternative stack guard page: Out of memory (os error 12)', library/std/src/sys/unix/stack_overflow.rs:147:13 backtrace=Backtrace [{ fn: "common_tracing::panic_hook::log_panic", file: "/workspace/src/common/tracing/src/panic_hook.rs", line: 35 }, { fn: "common_tracing::panic_hook::set_panic_hook::{{closure}}", file: "/workspace/src/common/tracing/src/panic_hook.rs", line: 30 }, { fn: "<alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs", line: 2032 }, { fn: "std::panicking::rust_panic_with_hook", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 692 }, { fn: "std::panicking::begin_panic_handler::{{closure}}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 579 }, { fn: "std::sys_common::backtrace::__rust_end_short_backtrace", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs", line: 137 }, { fn: "rust_begin_unwind", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 575 }, { fn: "core::panicking::panic_fmt", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panicking.rs", line: 64 }, { fn: "std::sys::unix::stack_overflow::imp::get_stackp", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/stack_overflow.rs", line: 147 }, { fn: "std::sys::unix::stack_overflow::imp::get_stack", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/stack_overflow.rs", line: 153 }, { fn: "std::sys::unix::stack_overflow::imp::make_handler", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/stack_overflow.rs", line: 164 }, { fn: "std::sys::unix::stack_overflow::Handler::new", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/stack_overflow.rs", line: 14 }, { fn: "std::sys::unix::thread::Thread::new::thread_start", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread.rs", line: 106 }] panic.file="library/std/src/sys/unix/stack_overflow.rs" panic.line=147 panic.column=13
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yufan022** [comment]
![d854062e-7ba3-4720-a821-28110c0f9f7e](https://user-images.githubusercontent.com/30121694/223042171-7125a9be-3e6e-49f5-896d-a3bbca2162f5.jpeg)

**Comment by BohuTANG** [comment]
Does this error related to this fix? https://github.com/datafuselabs/databend/pull/10300 @ariesdevil

**Comment by sundy-li** [comment]
it's oom panic:

```
Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }'
panicked at 'failed to set up alternative stack guard page: Out of memory (os error 12)', library/std/src/sys/unix/stack_overflow.rs:147:13 
```

**Comment by yufan022** [comment]
cat /proc/xx/status | grep Thread 
Threads:        1117

Many threads have leaked.

**Comment by yufan022** [comment]
May fixed by https://github.com/datafuselabs/databend/pull/10501

Verifying.
