### ISSUE TITLE
bug: databend-query start fail on termux

### ISSUE THREAD

**Issue by l1t1** [datafuselabs/databend#10935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

databend-v1.0.51-nightly-aarch64-unknown-linux-musl.tar.gz

### What's Wrong?

databend-meta started and then start databend-query failed. 

### How to Reproduce?

cd da/
tar xvf databend-v1.0.51-nightly-aarch64-unknown-linux-musl.tar.gz
bin/

cd da/

./bin/databend-meta -c bin/m.toml > meta.log 2>&1 &
sleep 2
curl -I  http://127.0.0.1:28101/v1/health

./bin/databend-query -c bin/q.toml > query.log 2>&1 &
sleep 2
curl -I  http://127.0.0.1:8080/v1/health

query.log
```
panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: ResolveError { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }) } }', /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.30.4/src/raw/http_util/client.rs:71:86
... 

Databend Query start failure, cause: Code: 1104, Text = called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: ResolveError { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }) } }.                                                                                                <Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable>           ~
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by l1t1** [comment]
bin/m.toml
```
# Usage:
# databend-meta -c databend-meta-node-1.toml

log_dir                 = "./.databend/logs1"
admin_api_address       = "0.0.0.0:28101"
grpc_api_address        = "0.0.0.0:9191"
# databend-query fetch this address to update its databend-meta endpoints list,
# in case databend-meta cluster changes.
grpc_api_advertise_host = "127.0.0.1"

[raft_config]
id            = 1
raft_dir      = "./.databend/meta1"
raft_api_port = 28103

# Assign raft_{listen|advertise}_host in test config.
# This allows you to catch a bug in unit tests when something goes wrong in raft meta nodes communication.
raft_listen_host = "127.0.0.1"
raft_advertise_host = "localhost"

# Start up mode: single node cluster
single        = true
```
bin/q.toml
```
# Usage:
# databend-query -c databend_query_config_spec.toml

[query]
max_active_sessions = 256
wait_timeout_mills = 5000

# For flight rpc.
flight_api_address = "0.0.0.0:9091"

# Databend Query http address.
# For admin RESET API.
admin_api_address = "0.0.0.0:8080"

# Databend Query metrics RESET API.
metric_api_address = "0.0.0.0:7070"

# Databend Query MySQL Handler.
mysql_handler_host = "0.0.0.0"
mysql_handler_port = 3307

# Databend Query ClickHouse Handler.
clickhouse_http_handler_host = "0.0.0.0"
clickhouse_http_handler_port = 8124

# Databend Query HTTP Handler.
http_handler_host = "0.0.0.0"
http_handler_port = 8000

tenant_id = "test_tenant"
cluster_id = "test_cluster"

table_engine_memory_enabled = true
default_storage_format = 'parquet'
default_compression = 'zstd'

# [[query.users]]
# name = "admin"
# auth_type = "no_password"

# [[query.users]]
# name = "databend"
# auth_type = "double_sha1_password"
# # echo -n "databend" | sha1sum | cut -d' ' -f1 | xxd -r -p | sha1sum
# auth_string = "3081f32caef285c232d066033c89a78d88a6d8a5"

# [[query.users]]
# name = "datafuselabs"
# auth_type = "sha256_password"
# #  echo -n "datafuselabs" | sha256sum
# auth_string = "6db1a2f5da402b43c066fcadcbf78f04260b3236d9035e44dd463f21e29e6f3b"


[log]

[log.file]
level = "INFO"
format = "text"
dir = "./.databend/logs_1"

[meta]
# It is a list of `grpc_api_advertise_host:<grpc-api-port>` of databend-meta config
endpoints = ["0.0.0.0:9191"]
username = "root"
password = "root"
client_timeout_in_second = 60
auto_sync_interval = 60

# Storage config.
[storage]
# fs | s3 | azblob | obs | oss
type = "fs"

# Set a local folder to store your data.
# Comment out this block if you're NOT using local file system as storage.
[storage.fs]
data_path = "./.databend/stateless_test_data"

# To use S3-compatible object storage, uncomment this block and set your values.
# [storage.s3]
# bucket = "<your-bucket-name>"
# endpoint_url = "<your-endpoint>"
# access_key_id = "<your-key-id>"
# secret_access_key = "<your-account-key>"
# enable_virtual_host_style = false

# To use Azure Blob storage, uncomment this block and set your values.
# [storage.azblob]
# endpoint_url = "https://<your-storage-account-name>.blob.core.windows.net"
# container = "<your-azure-storage-container-name>"
# account_name = "<your-storage-account-name>"
# account_key = "<your-account-key>"

# To use OBS object storage, uncomment this block and set your values.
# [storage.obs]
# bucket = "<your-bucket-name>"
# endpoint_url = "<your-endpoint>"
# access_key_id = "<your-key-id>"
# secret_access_key = "<your-account-key>"

# To use OSS object storage, uncomment this block and set your values.
# [storage.oss]
# bucket = "<your-bucket-name>"
# endpoint_url = "<your-endpoint>"
# access_key_id = "<your-key-id>"
# access_key_secret = "<your-account-key>"

# Cache config.
[cache]
# Type of storage to keep the table data cache
#
# available options: [none|disk]
# default is "none", which disable table data cache
# use "disk" to enabled disk cache
data_cache_storage = "none"

[cache.disk]
# cache path
path = "./.databend/_cache"
# max bytes of cached data 20G
max_bytes = 21474836480
```

**Comment by l1t1** [comment]
the script works fine with databend-v1.0.26-nightly-aarch64-unknown-linux-musl.tar.gz

**Comment by wubx** [comment]
panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: ResolveError { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }) } }', /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.30.4/src/raw/http_util/client.rs:71:86
... 

cc @xuanwo  Do you have any good suggestions? 
Print out the directories you can't find？

**Comment by wubx** [comment]
I'm following your initialization, and it feels like there are fewer steps
```
cd da
mkdir .databend
chown -R $USER .databend
```

**Comment by l1t1** [comment]
1.0.40 works fine too.  so it must be caused by recently modifications. 
```
~/da $ curl -LO https://repo.databend.rs/databend/v1.0.40-nightly/databend-v1.0.40-nightly-aarch64-unknown-linux-musl.tar.gz -C -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  232M  100  232M    0     0  4848k      0  0:00:49  0:00:49 --:--:-- 4484k
~/da $ tar xvf databend-v1.0.40-nightly-aarch64-unknown-linux-musl.tar.gz
bin/
bin/databend-meta
bin/databend-metabench
bin/databend-sqllogictests
bin/databend-metactl
bin/databend-meta-upgrade-09
bin/databend-query
configs/
configs/databend-query.toml
configs/databend-meta.toml
systemd/
systemd/databend-query.service
systemd/databend-meta.default
systemd/databend-query.default
systemd/databend-meta.service
scripts/
scripts/preinstall.sh
scripts/start.sh
scripts/stop.sh
scripts/postinstall.sh
readme.txt
~/da $ cd ..
~ $ ./da11                                                                                                HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
date: Fri, 07 Apr 2023 08:09:36 GMT

HTTP/1.1 200 OK
content-type: application/json; charset=utf-8
date: Fri, 07 Apr 2023 08:09:38 GMT

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 9
Server version: 8.0.26-v1.0.39-nightly-8b6c32b625f6198c035d819a25109ed3527dc2b8(rust-1.70.0-nightly-2023-03-29T17:12:15.422869276Z) 0

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]>
```

**Comment by l1t1** [comment]
this problem only occurs on ternux, 
1.0.58 works on kylin linux of aarch64 PC.
```
kylin@kylin:~/databend$ ps -ef|grep databend
kylin     9962     1  0 15:45 ?        00:00:00 engrampa /home/kylin/下载/databend-v1.0.58-nightly-aarch64-unknown-linux-musl.tar.gz
kylin    10021 13379  0 15:46 pts/1    00:00:00 grep --color=auto databend
kylin    13504 13379  0 3月21 pts/1   00:10:18 ./bin/databend-meta -c bin/m.toml
kylin    13545 13379  0 3月21 pts/1   00:02:48 ./bin/databend-query -c bin/q.toml
kylin@kylin:~/databend$ kill 13504
kylin@kylin:~/databend$ kill 13545
[1]-  已完成               ./bin/databend-meta -c bin/m.toml > meta.log 2>&1
kylin@kylin:~/databend$ 
[2]+  已完成               ./bin/databend-query -c bin/q.toml > query.log 2>&1
kylin@kylin:~/databend$ cd ..
kylin@kylin:~$ ./da
bash: ./da: 权限不够
kylin@kylin:~$ cd databend/
kylin@kylin:~/databend$ 
kylin@kylin:~/databend$ ./bin/databend-meta -c bin/m.toml > meta.log 2>&1 &
[1] 10242
kylin@kylin:~/databend$ 
kylin@kylin:~/databend$ ./bin/databend-query -c bin/q.toml > query.log 2>&1 &
[2] 10273
kylin@kylin:~/databend$ 
kylin@kylin:~/databend$ 
kylin@kylin:~/databend$ 
kylin@kylin:~/databend$ ./bendsql connect
Connected to Databend on Host: localhost
Version: DatabendQuery v1.0.58-nightly-0130fd131abcd408c99cfa591dff093d7f083d5d(rust-1.70.0-nightly-2023-04-09T16:47:27.491375963Z)
kylin@kylin:~/databend$ ./bendsql query
Connected with driver databend (DatabendQuery v1.0.58-nightly-0130fd131abcd408c99cfa591dff093d7f083d5d(rust-1.70.0-nightly-2023-04-09T16:47:27.491375963Z))
Type "help" for help.

dd:root@localhost/default=> 
dd:root@localhost/default=> select avg(number)from numbers(1000000000)group by round(log(number));
+-------------------+
|    avg(number)    |
+-------------------+
| 1.0               |
| 1237.0            |
| 167.5             |
| 74039886.0        |
| 62.0              |
| 3686229.0         |
| 899951088.4999999 |
| 547084872.0       |
| 24837.5           |
| 10020209.0        |
| 498877.0          |
| 67515.5           |
| 3361.5            |
| 8.5               |
| 27237752.0        |
| 183526.5          |
| 23.0              |
| 3.0               |
| 9137.0            |
| 455.0             |
| 201261277.0       |
| 1356088.0         |
| 0.0               |
+-------------------+
(23 rows)
```

**Comment by l1t1** [comment]
```
panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: ResolveError { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }) } }', /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.30.4/src/raw/http_util/client.rs:71:86
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/backtrace.rs:332:13
   3: common_tracing::panic_hook::log_panic
             at /workspace/src/common/tracing/src/panic_hook.rs:35:21
   4: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at /workspace/src/common/tracing/src/panic_hook.rs:30:9
   5: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/boxed.rs:2001:9
   6: std::panicking::rust_panic_with_hook
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:696:13
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:583:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:150:18
   9: rust_begin_unwind
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:579:5
  10: core::panicking::panic_fmt
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panicking.rs:64:14
  11: core::result::unwrap_failed
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/result.rs:1750:5
  12: core::result::Result<T,E>::unwrap
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/result.rs:1090:23
  13: opendal::raw::http_util::client::HttpClient::new
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/opendal-0.30.4/src/raw/http_util/client.rs:71:57
  14: common_sharing::share_endpoint::ShareEndpointManager::init
             at /workspace/src/query/sharing/src/share_endpoint.rs:53:21
  15: databend_query::global_services::GlobalServices::init_with::{{closure}}::{{closure}}
             at /workspace/src/query/service/src/global_services.rs:82:9
  16: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/framed.rs:49:27
  17: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:184:17
  18: std::thread::local::LocalKey<T>::try_with
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  19: std::thread::local::LocalKey<T>::with
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  20: async_backtrace::frame::active_frame::with
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:81:9
  21: async_backtrace::frame::Frame::in_scope
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:180:13
  22: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/framed.rs:49:9
  23: databend_query::global_services::GlobalServices::init_with::{{closure}}
             at /workspace/src/query/service/src/global_services.rs:46:5
  24: databend_query::global_services::GlobalServices::init::{{closure}}::{{closure}}
             at /workspace/src/query/service/src/global_services.rs:43:42
  25: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/framed.rs:49:27
  26: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:184:17
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  29: async_backtrace::frame::active_frame::with
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:81:9
  30: async_backtrace::frame::Frame::in_scope
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:180:13
  31: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/framed.rs:49:9
  32: databend_query::global_services::GlobalServices::init::{{closure}}
             at /workspace/src/query/service/src/global_services.rs:40:5
  33: databend_query::main_entrypoint::{{closure}}
             at /workspace/src/binaries/query/main.rs:92:39
  34: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/framed.rs:49:27
  35: async_backtrace::frame::Frame::in_scope::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:184:17
  36: std::thread::local::LocalKey<T>::try_with
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  37: std::thread::local::LocalKey<T>::with
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  38: async_backtrace::frame::active_frame::with
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:81:9
  39: async_backtrace::frame::Frame::in_scope
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/frame.rs:180:13
  40: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/framed.rs:49:9
  41: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll{{reify.shim}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.4/src/framed.rs:45:5
  42: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
  43: futures_util::future::future::FutureExt::poll_unpin
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/future/mod.rs:562:9
  44: <common_base::runtime::catch_unwind::CatchUnwindFuture<F> as core::future::future::Future>::poll::{{closure}}
             at /workspace/src/common/base/src/runtime/catch_unwind.rs:54:36
  45: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panic/unwind_safe.rs:271:9
  46: std::panicking::try::do_call
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
  47: std::panicking::try
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
  48: std::panic::catch_unwind
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
  49: common_base::runtime::catch_unwind::catch_unwind
             at /workspace/src/common/base/src/runtime/catch_unwind.rs:26:11
  50: <common_base::runtime::catch_unwind::CatchUnwindFuture<F> as core::future::future::Future>::poll
             at /workspace/src/common/base/src/runtime/catch_unwind.rs:54:15
  51: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/park.rs:283:63
  52: tokio::runtime::coop::with_budget
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:107:5
  53: tokio::runtime::coop::budget
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:73:5
  54: tokio::runtime::park::CachedParkThread::block_on
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/park.rs:283:31
  55: tokio::runtime::context::BlockingRegionGuard::block_on
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/context.rs:315:13
  56: tokio::runtime::handle::Handle::block_on
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/handle.rs:264:9
  57: common_base::runtime::runtime::Runtime::block_on
             at /workspace/src/common/base/src/runtime/runtime.rs:206:9
  58: databend_query::main
             at /workspace/src/binaries/query/main.rs:57:33
  59: core::ops::function::FnOnce::call_once
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/ops/function.rs:250:5
  60: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:134:18
  61: std::rt::lang_start::{{closure}}
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/rt.rs:166:18
  62: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/ops/function.rs:287:13
  63: std::panicking::try::do_call
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
  64: std::panicking::try
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
  65: std::panic::catch_unwind
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
  66: std::rt::lang_start_internal::{{closure}}
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/rt.rs:148:48
  67: std::panicking::try::do_call
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
  68: std::panicking::try
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
  69: std::panic::catch_unwind
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
  70: std::rt::lang_start_internal
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/rt.rs:148:20
  71: main

Databend Query start failure, cause: Code: 1104, Text = called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: ResolveError { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }) } }.

   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/backtrace.rs:332:13
   3: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::PanicError
             at /workspace/src/common/exception/src/exception_code.rs:38:71
   4: common_base::runtime::catch_unwind::catch_unwind
             at /workspace/src/common/base/src/runtime/catch_unwind.rs:31:38
   5: <common_base::runtime::catch_unwind::CatchUnwindFuture<F> as core::future::future::Future>::poll
             at /workspace/src/common/base/src/runtime/catch_unwind.rs:54:15
   6: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/park.rs:283:63
   7: tokio::runtime::coop::with_budget
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:107:5
   8: tokio::runtime::coop::budget
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/coop.rs:73:5
   9: tokio::runtime::park::CachedParkThread::block_on
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/park.rs:283:31
  10: tokio::runtime::context::BlockingRegionGuard::block_on
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/context.rs:315:13
  11: tokio::runtime::handle::Handle::block_on
             at /opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.26.0/src/runtime/handle.rs:264:9
  12: common_base::runtime::runtime::Runtime::block_on
             at /workspace/src/common/base/src/runtime/runtime.rs:206:9
  13: databend_query::main
             at /workspace/src/binaries/query/main.rs:57:33
  14: core::ops::function::FnOnce::call_once
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/ops/function.rs:250:5
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:134:18
  16: std::rt::lang_start::{{closure}}
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/rt.rs:166:18
  17: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/ops/function.rs:287:13
  18: std::panicking::try::do_call
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
  19: std::panicking::try
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
  20: std::panic::catch_unwind
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
  21: std::rt::lang_start_internal::{{closure}}
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/rt.rs:148:48
  22: std::panicking::try::do_call
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
  23: std::panicking::try
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
  24: std::panic::catch_unwind
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
  25: std::rt::lang_start_internal
             at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/rt.rs:148:20
  26: main
```
