### ISSUE TITLE
Flaky test: `api::http::cluster_state_test::test_http_service_cluster_state`

### ISSUE THREAD

**Issue by xudong963** [datafuselabs/databend#10943]
https://github.com/datafuselabs/databend/actions/runs/4615783776/jobs/8160020013?pr=10940
flaky test:

```
failures:

---- api::http::cluster_state_test::test_http_service_cluster_state stdout ----
thread 'api::http::cluster_state_test::test_http_service_cluster_state' panicked at 'assertion failed: resp.is_ok()', src/meta/service/tests/it/api/http/cluster_state_test.rs:171:5
stack backtrace:
   0:     0x564580588cca - std::backtrace_rs::backtrace::libunwind::trace::hbc48ddb4bcf57554
                               at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x564580588cca - std::backtrace_rs::backtrace::trace_unsynchronized::h9673e7a745f884fe
                               at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x564580588cca - std::sys_common::backtrace::_print_fmt::hb8bf1b68b7a7c088
                               at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x564580588cca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h58e645a0bb1f823d
                               at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5645805b70be - core::fmt::write::h1dcfda4149fb823c
                               at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/fmt/mod.rs:1232:17
   5:     0x564580583925 - std::io::Write::write_fmt::h85eb1e1960c6d51b
                               at /rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/io/mod.rs:1684:15
   6:     0x564580588a95 - std::sys_common::backtrace::_print::h9fb7289281efd86a
```

_Originally posted by @xudong963 in https://github.com/datafuselabs/databend/issues/10940#issuecomment-1497031523_

**Comment by youngsofun** [comment]
see it again

https://github.com/datafuselabs/databend/actions/runs/5375156782/jobs/9752192611

**Comment by youngsofun** [comment]
cc @drmingdrmer

**Comment by drmingdrmer** [comment]
`start()` does not block until the service starting up. There is a chance the client tries to connect to it before service ready.

Let me fix it.

https://github.com/datafuselabs/databend/blob/9990d6c3b68ce0b9f22d104c38c2677649c5559b/src/meta/service/tests/it/api/http/cluster_state_test.rs#L164-L171
