### ISSUE TITLE
bug: musl build segmentation fault caused by z3/src/api/api_arith.cpp:196

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#11116]
**Summary**

```
wget https://github.com/datafuselabs/databend/releases/download/v1.0.60-nightly/databend-v1.0.60-nightly-x86_64-unknown-linux-musl.tar.gz
```

Start with GDB:
```
Starting program: /root/databend/databend-query-160 -c ./databend-query.toml
[New LWP 770462]
[New LWP 770463]

Thread 1 "databend-query-" received signal SIGSEGV, Segmentation fault.
0x00000000005959d6 in ?? ()
(gdb) bt
#0  0x00000000005959d6 in ?? ()
#1  0x00007fffefc69840 in __static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1) at /usr/local/x86_64-linux-musl/include/c++/9.4.0/iostream:74
#2  _GLOBAL__sub_I_api_arith.cpp(void) () at /opt/rust/cargo/registry/src/[index.crates.io](http://index.crates.io/)-6f17d22bba15001f/z3-sys-0.7.1/z3/src/api/api_arith.cpp:196
#3  0x00007ffff655e794 in libc_start_init () at ../src_musl/src/env/__libc_start_main.c:64
#4  0x00007ffff655e7b9 in libc_start_main_stage2 () at ../src_musl/src/env/__libc_start_main.c:91
#5  0x00007fffefc72746 in _start ()
```

**Comment by BohuTANG** [comment]
cc @leiysky
