### ISSUE TITLE
bug: Recluster Table ERROR, Cannot join handle from context's runtime, cause: task XX panicked.

### ISSUE THREAD

**Issue by Px951213** [datafuselabs/databend#11723]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

8.0.26-v1.1.46-nightly-377d21f7f0675bb6b08a02d79df65aa3c9975a4c(rust-1.70.0-nightly-2023-05-24T16:07:06.096155586Z)

### What's Wrong?

when running sql below，a panic error was thrown
```sql
ALTER TABLE XX RECLUSTER FINAL;
ERROR 1105 (HY000): Code: 1068, Text = Cannot join handle from context's runtime, cause: task 21806 panicked.
```

**Table schema：**
CREATE TABLE `XX` (
 ....
) ENGINE=FUSE CLUSTER BY (to_date(TO_TIMESTAMP(created_at)), sid, deleted) 

### How to Reproduce?

above

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by dantengsky** [comment]
@zhyass  please have a look.

**Comment by zhyass** [comment]
Hi, @Px951213 
how many segments and blocks are there in this table? (you can check them via fuse_snapshot). And can you provide a more detailed error stack trace?

**Comment by Px951213** [comment]
> Hi, @Px951213 How many segments and blocks are there in this table? (you can check them via [fuse_snapshot](https://databend.rs/doc/sql-functions/system-functions/fuse_snapshot)). And can you provide a more detailed error stack trace?

there are 56 segments and 58190 blocks( per_block_uncompressed_size: 987.83 KiB).

stack trace:
```
panicked at 'called `Option::unwrap()` on a `None` value', src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:164:62
   0: common_tracing::panic_hook::log_panic
             at ./workspace/src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./workspace/src/common/tracing/src/panic_hook.rs:30:9
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/boxed.rs:2001:9
   3: std::panicking::rust_panic_with_hook
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:696:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:581:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:150:18
   6: rust_begin_unwind
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:579:5
   7: core::panicking::panic_fmt
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panicking.rs:64:14
   8: core::panicking::panic
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panicking.rs:114:5
   9: core::option::Option<T>::unwrap
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/option.rs:942:21
  10: <common_storages_fuse::operations::mutation::recluster_mutator::ReclusterMutator as common_catalog::table_mutator::TableMutator>::target_select::{{closure}}::{{closure}}::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:164:32
  11: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::for_each
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/slice/iter/macros.rs:201:21
  12: <common_storages_fuse::operations::mutation::recluster_mutator::ReclusterMutator as common_catalog::table_mutator::TableMutator>::target_select::{{closure}}::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:163:17
  13: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  14: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  15: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  16: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  17: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  18: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  19: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  20: <common_storages_fuse::operations::mutation::recluster_mutator::ReclusterMutator as common_catalog::table_mutator::TableMutator>::target_select::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:91:5
  21: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
  22: common_storages_fuse::operations::recluster::<impl common_storages_fuse::fuse_table::FuseTable>::do_recluster::{{closure}}::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/recluster.rs:108:53
  23: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  24: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  25: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  26: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  27: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  28: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  29: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  30: common_storages_fuse::operations::recluster::<impl common_storages_fuse::fuse_table::FuseTable>::do_recluster::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/recluster.rs:48:5
  31: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::recluster::{{closure}}::{{closure}}
             at ./workspace/src/query/storages/fuse/src/fuse_table.rs:696:53
  32: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  33: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  34: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  35: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  36: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  37: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  38: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  39: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::recluster::{{closure}}
             at ./workspace/src/query/storages/fuse/src/fuse_table.rs:689:5
  40: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
  41: <databend_query::interpreters::interpreter_table_recluster::ReclusterTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter_table_recluster.rs:81:17
  42: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  43: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  44: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  45: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  46: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  47: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  48: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  49: <databend_query::interpreters::interpreter_table_recluster::ReclusterTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter_table_recluster.rs:48:5
  50: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
  51: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter.rs:61:50
  52: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  53: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  54: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  55: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  56: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  57: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  58: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  59: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter.rs:51:5
  60: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
 .....
```

**Comment by zhyass** [comment]
> 1: common_tracing::panic_hook::set_panic_hook::{{closure}}
>              at ./workspace/src/common/tracing/src/panic_hook.rs:30:9

Thanks, I already know the location of error and I will try to reproduce it locally.
