### ISSUE TITLE
Bug: expected get the OOM error but got `1104: interpreter panic: Any { .. }`

### ISSUE THREAD

**Issue by flaneur2020** [datafuselabs/databend#11733]
**Summary**

I was triggered into an OOM issue while executing `alter table xxx recluster`:

```
panicked at 'memory usage 32.0 GB(32000321163) exceeds limit 32.0 GB(32000000000)', src/common/base/src/runtime/runtime_tracker.rs:84:9
   0: common_tracing::panic_hook::log_panic
             at ./workspace/src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./workspace/src/common/tracing/src/panic_hook.rs:30:9
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/boxed.rs:2001:9
   3: std::panicking::rust_panic_with_hook
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:696:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:583:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:150:18
   6: rust_begin_unwind
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:579:5
   7: core::panicking::panic_fmt
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panicking.rs:64:14
   8: core::panicking::panic_display
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panicking.rs:147:5
   9: common_base::runtime::runtime_tracker::set_alloc_error_hook::{{closure}}
             at ./workspace/src/common/base/src/runtime/runtime_tracker.rs:84:9
  10: core::ops::function::FnOnce::call_once
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/ops/function.rs:250:5
  11: std::alloc::rust_oom
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/alloc.rs:355:5
  12: __rg_oom
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/alloc.rs:351:1
  13: __rust_alloc_error_handler
  14: alloc::alloc::handle_alloc_error::rt_error
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/alloc.rs:385:13
  15: alloc::alloc::handle_alloc_error
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/alloc.rs:389:14
  16: alloc::raw_vec::RawVec<T,A>::allocate_in
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/raw_vec.rs:190:27
  17: alloc::raw_vec::RawVec<T,A>::with_capacity_in
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/raw_vec.rs:131:9
  18: alloc::vec::Vec<T,A>::with_capacity_in
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/vec/mod.rs:676:20
  19: alloc::vec::Vec<T>::with_capacity
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/vec/mod.rs:483:9
  20: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/vec/spec_from_iter_nested.rs:32:34
  21: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/vec/spec_from_iter.rs:33:9
  22: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/vec/mod.rs:2724:9
  23: core::iter::traits::iterator::Iterator::collect
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/iter/traits/iterator.rs:1891:9
  24: common_storages_fuse::operations::mutation::recluster_mutator::ReclusterMutator::target_select::{{closure}}::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:142:37
  25: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  26: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  27: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  28: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  29: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  30: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  31: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  32: common_storages_fuse::operations::mutation::recluster_mutator::ReclusterMutator::target_select::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/mutation/recluster_mutator.rs:66:5
  33: common_storages_fuse::operations::recluster::<impl common_storages_fuse::fuse_table::FuseTable>::do_recluster::{{closure}}::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/recluster.rs:107:63
  34: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  35: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  36: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  37: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  38: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  39: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  40: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  41: common_storages_fuse::operations::recluster::<impl common_storages_fuse::fuse_table::FuseTable>::do_recluster::{{closure}}
             at ./workspace/src/query/storages/fuse/src/operations/recluster.rs:52:5
  42: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::recluster::{{closure}}::{{closure}}
             at ./workspace/src/query/storages/fuse/src/fuse_table.rs:683:53
  43: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  44: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  45: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  46: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  47: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  48: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  49: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  50: <common_storages_fuse::fuse_table::FuseTable as common_catalog::table::Table>::recluster::{{closure}}
             at ./workspace/src/query/storages/fuse/src/fuse_table.rs:676:5
  51: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
  52: <databend_query::interpreters::interpreter_table_recluster::ReclusterTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter_table_recluster.rs:81:17
  53: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  54: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  55: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  56: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  57: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  58: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  59: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  60: <databend_query::interpreters::interpreter_table_recluster::ReclusterTableInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter_table_recluster.rs:48:5
  61: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
  62: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter.rs:61:50
  63: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  64: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  65: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  66: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  67: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  68: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  69: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  70: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter.rs:51:5
  71: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/future/future.rs:125:9
  72: databend_query::servers::http::v1::query::execute_state::execute::{{closure}}
             at ./workspace/src/query/service/src/servers/http/v1/query/execute_state.rs:268:59
  73: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panic/unwind_safe.rs:296:9
  74: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/future/catch_unwind.rs:36:42
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
  77: std::panicking::try
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
  78: std::panic::catch_unwind
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
  79: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.27/src/future/future/catch_unwind.rs:36:9
  80: databend_query::servers::http::v1::query::execute_state::ExecuteState::try_start_query::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/servers/http/v1/query/execute_state.rs:242:51
  81: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  82: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  83: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  84: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  85: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  86: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  87: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  88: databend_query::servers::http::v1::query::execute_state::ExecuteState::try_start_query::{{closure}}
             at ./workspace/src/query/service/src/servers/http/v1/query/execute_state.rs:219:5
  89: databend_query::servers::http::v1::query::http_query::HttpQuery::try_create::{{closure}}::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/servers/http/v1/query/http_query.rs:321:17
  90: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  91: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  92: std::thread::local::LocalKey<T>::try_with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:446:16
  93: std::thread::local::LocalKey<T>::with
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/local.rs:422:9
  94: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  95: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  96: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  97: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
  98: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
  99: tokio::runtime::task::core::Core<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
 100: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
 101: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panic/unwind_safe.rs:271:9
 102: std::panicking::try::do_call
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
 103: std::panicking::try
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
 104: std::panic::catch_unwind
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
 105: tokio::runtime::task::harness::poll_future
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
 106: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
 107: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
 108: tokio::runtime::task::raw::RawTask::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
 109: tokio::runtime::task::LocalNotified<S>::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:394:9
 110: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
 111: tokio::runtime::coop::with_budget
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:107:5
 112: tokio::runtime::coop::budget
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/coop.rs:73:5
 113: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
 114: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:426:24
 115: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
 116: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/macros/scoped_tls.rs:61:9
 117: tokio::runtime::scheduler::multi_thread::worker::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
 118: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
 119: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/task.rs:42:21
 120: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:223:17
 121: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/loom/std/unsafe_cell.rs:14:9
 122: tokio::runtime::task::core::Core<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/core.rs:212:13
 123: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:476:19
 124: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panic/unwind_safe.rs:271:9
 125: std::panicking::try::do_call
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
 126: std::panicking::try
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
 127: std::panic::catch_unwind
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
 128: tokio::runtime::task::harness::poll_future
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:464:18
 129: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:198:27
 130: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/harness.rs:152:15
 131: tokio::runtime::task::raw::RawTask::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/raw.rs:200:18
 132: tokio::runtime::task::UnownedTask<S>::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/task/mod.rs:431:9
 133: tokio::runtime::blocking::pool::Task::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:159:9
 134: tokio::runtime::blocking::pool::Inner::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:513:17
 135: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.0/src/runtime/blocking/pool.rs:471:13
 136: std::sys_common::backtrace::__rust_begin_short_backtrace
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys_common/backtrace.rs:134:18
 137: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/mod.rs:560:17
 138: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/panic/unwind_safe.rs:271:9
 139: std::panicking::try::do_call
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:487:40
 140: std::panicking::try
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panicking.rs:451:19
 141: std::panic::catch_unwind
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/panic.rs:140:14
 142: std::thread::Builder::spawn_unchecked_::{{closure}}
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/thread/mod.rs:559:30
 143: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/core/src/ops/function.rs:250:5
 144: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/boxed.rs:1987:9
 145: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/alloc/src/boxed.rs:1987:9
 146: std::sys::unix::thread::Thread::new::thread_start
             at ./rustc/39f2657d1101b50f9b71ae460b762d330cc8426b/library/std/src/sys/unix/thread.rs:108:17
 147: start_thread
 148: clone

  [2m2023-06-12T10:48:25.102859Z[0m [31mERROR[0m [1;31mcommon_tracing::pa
```

I could found out it's an OOM in the logs with RUST_BACKTRACE enabled.

but it'd be better to have the error message in the error response instead of `interpreter panic`:

```
1104: interpreter panic: Any { .. }
```

**Comment by BohuTANG** [comment]
cc @zhang2014
