### ISSUE TITLE
bug: optimize table compact (with reclustering) failed with `ERROR 1105 (HY000): Code: 1104, Text = assertion failed: mid <= self.len().`

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#11983]
**Summary**

while pressure testing https://github.com/datafuselabs/databend/pull/11917 ; 

after row numbers of the table increased to about 319,815,000,  

`optimize table t compact`

failed.

**test box:**

linux + single node + local fs 

~~~
MySQL [test]> optimize table test.test_order compact;
ERROR 1105 (HY000): Code: 1104, Text = assertion failed: mid <= self.len().
~~~

server log

~~~
panicked at 'assertion failed: mid <= self.len()', /home/wu/.cargo/git/checkouts/arrow2-8a2ad61d97265680/d1240b6/src/io/parquet/read/deserialize/binary/utils.rs:132:45
   0: common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
   3: rust_panic_with_hook
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:709:13
   4: {closure#0}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:595:13
   5: __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:151:18
   6: begin_panic_handler
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:593:5
   7: panic_fmt
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:67:14
   8: panic
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:117:5
   9: <arrow2::io::parquet::read::deserialize::binary::basic::BinaryDecoder<O> as arrow2::io::parquet::read::deserialize::utils::Decoder>::extend_from_state
  10: arrow2::io::parquet::read::deserialize::utils::extend_from_new_page
             at /home/wu/.cargo/git/checkouts/arrow2-8a2ad61d97265680/d1240b6/src/io/parquet/read/deserialize/utils.rs:425:5
  11: arrow2::io::parquet::read::deserialize::utils::next
             at /home/wu/.cargo/git/checkouts/arrow2-8a2ad61d97265680/d1240b6/src/io/parquet/read/deserialize/utils.rs:491:13
  12: <arrow2::io::parquet::read::deserialize::binary::basic::Iter<O,I> as core::iter::traits::iterator::Iterator>::next
             at /home/wu/.cargo/git/checkouts/arrow2-8a2ad61d97265680/d1240b6/src/io/parquet/read/deserialize/binary/basic.rs:498:27
  13: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1919:9
  14: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/adapters/map.rs:103:9
  15: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1919:9
  16: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/adapters/map.rs:103:9
  17: <alloc::boxed::Box<I,A> as core::iter::traits::iterator::Iterator>::next
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1919:9
  18: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_field
             at ./src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs:291:25
  19: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_parquet_chunks_with_buffer
             at ./src/query/storages/fuse/src/io/read/block/block_reader_parquet_deserialize.rs:111:19
  20: <common_storages_fuse::operations::read::parquet_data_source_deserializer::DeserializeDataTransform as common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/storages/fuse/src/operations/read/parquet_data_source_deserializer.rs:154:38
  21: <alloc::boxed::Box<T> as common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/pipeline/core/src/processors/processor.rs:138:9
  22: common_pipeline_core::processors::processor::ProcessorPtr::process
             at ./src/query/pipeline/core/src/processors/processor.rs:110:9
  23: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:82:9
  24: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:73:46
  25: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:375:45
  26: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:331:27
  27: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  28: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  29: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  30: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  31: common_base::runtime::catch_unwind::catch_unwind
             at ./src/common/base/src/runtime/catch_unwind.rs:26:11
  32: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:330:34
  33: common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at ./src/common/base/src/runtime/thread.rs:85:21
  34: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
  35: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
  36: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  37: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  38: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  39: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  40: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:528:30
  41: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  42: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  43: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  44: thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
  45: start_thread
             at ./nptl/pthread_create.c:442:8
  46: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
~~~

**Comment by dantengsky** [comment]
panics which accessing col "s10" of the following parquet file:

[2546b3c8b64e4b8e9d598751c8599bc0_v2.parquet.gz](https://github.com/datafuselabs/databend/files/11959367/2546b3c8b64e4b8e9d598751c8599bc0_v2.parquet.gz)

**Comment by dantengsky** [comment]
no longer happening
