### ISSUE TITLE
bug: chown: invalid user: ‘builder’

### ISSUE THREAD

**Issue by thomas-k-cameron** [datafuselabs/databend#12393]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

commit hash: dc621fba5f6590fd3eac87f5b9c9c05a54c6892d

### What's Wrong?

It fails to create dev container.

Based on the log, it seems like it's the problem with the user.
```
#7 [dev_container_auto_added_stage_label 3/3] RUN mkdir /home/builder && chown -R builder /home/builder &&     usermod --shell /bin/bash builder
#7 0.456 chown: invalid user: ‘builder’
#7 ERROR: process "/bin/sh -c mkdir /home/builder && chown -R builder /home/builder &&     usermod --shell /bin/bash builder" did not complete successfully: exit code: 1
------
 > [dev_container_auto_added_stage_label 3/3] RUN mkdir /home/builder && chown -R builder /home/builder &&     usermod --shell /bin/bash builder:
0.456 chown: invalid user: ‘builder’
------
Dockerfile-with-features:16
--------------------
  15 |     
  16 | >>> RUN mkdir /home/builder && chown -R builder /home/builder && \
  17 | >>>     usermod --shell /bin/bash builder
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c mkdir /home/builder && chown -R builder /home/builder &&     usermod --shell /bin/bash builder" did not complete successfully: exit code: 1
[58198 ms] Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.48.0-1691559056139/Dockerfile-with-features -t vsc-databend-dc58afc70bbe2adb0571cf4df0c017cd73013b0fded74db8691ca006d8f6da8e --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/databend/.devcontainer
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.48.0-1691559056139/Dockerfile-with-features -t vsc-databend-dc58afc70bbe2adb0571cf4df0c017cd73013b0fded74db8691ca006d8f6da8e --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/databend/.devcontainer
{"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.48.0-1691559056139/Dockerfile-with-features -t vsc-databend-dc58afc70bbe2adb0571cf4df0c017cd73013b0fded74db8691ca006d8f6da8e --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/databend/.devcontainer","description":"An error occurred building the image."}
    at Mte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2008:1698)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async cC (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2007:1691)
    at async e3 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2007:610)
    at async Qte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:3660)
    at async Kf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2024:4775)
    at async xne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2156:12125)
    at async wne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2156:11866)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.48.0-1691559056139/Dockerfile-with-features -t vsc-databend-dc58afc70bbe2adb0571cf4df0c017cd73013b0fded74db8691ca006d8f6da8e --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label /var/lib/docker/codespacemount/workspace/databend/.devcontainer
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.
```

### How to Reproduce?

Try to use github code spaces.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by everpcpc** [comment]
Hi, could you please try this https://github.com/datafuselabs/databend/pull/12402 ?

**Comment by thomas-k-cameron** [comment]
Thanks, let me try it.

**Comment by thomas-k-cameron** [comment]
It worked. Thanks a lot. @everpcpc
