### ISSUE TITLE
bug: group by grouping set panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#12790]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.107-nightly

### What's Wrong?

group by grouping set panic
```
panicked at 'memory allocation of 144115187963736679 bytes failed', src/common/base/src/runtime/runtime_tracker.rs:84:9
   0: common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
   3: rust_panic_with_hook
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:709:13
   4: {closure#0}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:597:13
   5: __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:151:18
   6: begin_panic_handler
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:593:5
   7: panic_fmt
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:67:14
   8: core::panicking::panic_display
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:150:5
   9: common_base::runtime::runtime_tracker::set_alloc_error_hook::{{closure}}
             at ./src/common/base/src/runtime/runtime_tracker.rs:84:9
  10: core::ops::function::FnOnce::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  11: rust_oom
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/alloc.rs:355:5
  12: __rg_oom
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/alloc.rs:351:1
  13: alloc::alloc::handle_alloc_error::rt_error
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/alloc.rs:387:13
  14: alloc::alloc::handle_alloc_error
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/alloc.rs:391:14
  15: alloc::raw_vec::handle_reserve
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/raw_vec.rs:496:43
  16: alloc::raw_vec::RawVec<T,A>::reserve::do_reserve_and_handle
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/raw_vec.rs:289:13
  17: alloc::vec::Vec<T,A>::reserve
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/raw_vec.rs:293:13
  18: alloc::vec::Vec<T,A>::extend_with
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/mod.rs:2476:9
  19: alloc::vec::Vec<T,A>::resize
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/mod.rs:2358:13
  20: common_expression::values::ColumnBuilder::push_binary
             at ./src/query/expression/src/values.rs:2224:17
  21: common_expression::values::ColumnBuilder::push_binary
             at ./src/query/expression/src/values.rs:2259:21
  22: <databend_query::pipelines::processors::transforms::group_by::aggregator_groups_builder::SerializedKeysGroupColumnsBuilder as databend_query::pipelines::processors::transforms::group_by::aggregator_groups_builder::GroupColumnsBuilder>::finish
             at ./src/query/service/src/pipelines/processors/transforms/group_by/aggregator_groups_builder.rs:135:17
  23: <databend_query::pipelines::processors::transforms::aggregator::transform_group_by_final::TransformFinalGroupBy<Method> as common_pipeline_transforms::processors::transforms::transform::BlockMetaTransform<databend_query::pipelines::processors::transforms::aggregator::aggregate_meta::AggregateMeta<Method,()>>>::transform
             at ./src/query/service/src/pipelines/processors/transforms/aggregator/transform_group_by_final.rs:115:51
  24: <common_pipeline_transforms::processors::transforms::transform::BlockMetaTransformer<B,T> as common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/pipeline/transforms/src/processors/transforms/transform.rs:306:37
  25: <alloc::boxed::Box<T> as common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/pipeline/core/src/processors/processor.rs:159:9
  26: <alloc::boxed::Box<T> as common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/pipeline/core/src/processors/processor.rs:159:9
  27: common_pipeline_core::processors::processor::ProcessorPtr::process
             at ./src/query/pipeline/core/src/processors/processor.rs:127:9
  28: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:82:9
  29: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:73:46
  30: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:376:45
  31: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:332:27
  32: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  33: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  34: __rust_try
  35: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  36: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  37: common_base::runtime::catch_unwind::catch_unwind
             at ./src/common/base/src/runtime/catch_unwind.rs:26:11
  38: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:331:34
  39: common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at ./src/common/base/src/runtime/thread.rs:85:21
  40: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
  41: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
  42: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  43: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  44: __rust_try
  45: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  46: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  47: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  48: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  49: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  50: thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
  51: <unknown>
  52: <unknown>
```

### How to Reproduce?

```sql
mysql> create table test (a uint64);
Query OK, 0 rows affected (0.06 sec)

mysql> insert into test values(1682080366),(3244090908),(2078492037),(893066009),(NULL),(NULL),(577768562),(806932999),(576225075),(2137776719),(NULL),(4145365235),(NULL),(NULL),(2389662822),(3586919571),(934040586),(4056702422),(3699451264),(3496066951),(1099928536),(NULL),(NULL),(1712339209),(350553990),(NULL),(NULL),(1396160123),(NULL),(1675393051),(4194854024),(2972316441),(NULL),(1159182636),(2697201495),(569763706),(NULL),(NULL),(NULL),(447028653),(571104721),(1400241069),(NULL),(706722730),(216455292),(NULL),(702510985),(NULL),(NULL),(970077576);Query OK, 50 rows affected (0.04 sec)

mysql> SELECT -0.000000000000000000000000000000000673299310, [], minus(a), to_bitmap(837), to_bitmap(526) FROM test GROUP BY GROUPING SETS ((-0.000000000000000000000000000000000673299310, [], minus(a), to_bitmap(837), to_bitmap(526)));
ERROR 1105 (HY000): PanicError. Code: 1104, Text = memory allocation of 144115187963736679 bytes failed.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by b41sh** [comment]
after PR #12797 merged, query will not panic, but the result seems not correct.
```sql
mysql> SELECT -0.000000000000000000000000000000000673299310, [], minus(a), to_bitmap(837), to_bitmap(526) FROM test GROUP BY GROUPING SETS ((-0.000000000000000000000000000000000673299310, [], minus(a), to_bitmap(837), to_bitmap(526)));
+--------------------------------------------------+------+-------------+-----------------+----------------+
| (- 0.000000000000000000000000000000000673299310) | []   | minus(a)    | to_bitmap(837)  | to_bitmap(526) |
+--------------------------------------------------+------+-------------+-----------------+----------------+
|    -0.000000000000000000000000000000000673299310 | []   | -1712339209 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -577768562 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -1396160123 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -2972316441 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -576225075 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -350553990 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -806932999 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -3244090908 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -1682080366 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -706722730 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -569763706 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -3586919571 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -216455292 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -970077576 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -1099928536 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -2137776719 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -1400241069 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -893066009 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -4145365235 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |        NULL | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -571104721 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -1675393051 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -702510985 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -3496066951 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -934040586 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   |  -447028653 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -2697201495 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -2078492037 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -1159182636 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -3699451264 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -2389662822 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -4194854024 | <bitmap binary> | NULL           |
|    -0.000000000000000000000000000000000673299310 | []   | -4056702422 | <bitmap binary> | NULL           |
+--------------------------------------------------+------+-------------+-----------------+----------------+
33 rows in set (0.04 sec)
Read 50 rows, 407.00 B in 0.010 sec., 4.77 thousand rows/sec., 37.92 KiB/sec.
```

**Comment by ariesdevil** [comment]
#12821
