### ISSUE TITLE
bug: table add column panic

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#12943]
**Summary**

```
panicked at 'insertion index (is 9) should be <= len (is 0)', library/alloc/src/vec/mod.rs:1439:13
   0: common_tracing::panic_hook::log_panic
             at ./workspace/src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./workspace/src/common/tracing/src/panic_hook.rs:30:9
   2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
   3: rust_panic_with_hook
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:709:13
   4: {closure#0}
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:597:13
   5: __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:151:18
   6: begin_panic_handler
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:593:5
   7: panic_fmt
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:67:14
   8: assert_failed
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/mod.rs:1439:13
   9: alloc::vec::Vec<T,A>::insert
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/mod.rs:1461:21
  10: common_meta_app::schema::table::TableMeta::add_column
             at ./workspace/src/meta/app/src/schema/table.rs:265:9
  11: <databend_query::interpreters::interpreter_table_add_column::AddTableColumnInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter_table_add_column.rs:103:13
  12: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  13: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  14: std::thread::local::LocalKey<T>::try_with
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  15: std::thread::local::LocalKey<T>::with
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  16: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  17: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  18: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  19: <databend_query::interpreters::interpreter_table_add_column::AddTableColumnInterpreter as databend_query::interpreters::interpreter::Interpreter>::execute2::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter_table_add_column.rs:53:5
  20: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  21: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter.rs:55:51
  22: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  23: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  24: std::thread::local::LocalKey<T>::try_with
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  25: std::thread::local::LocalKey<T>::with
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  26: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  27: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  28: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  29: databend_query::interpreters::interpreter::Interpreter::execute::{{closure}}
             at ./workspace/src/query/service/src/interpreters/interpreter.rs:45:5
  30: <core::pin::Pin<P> as core::future::future::Future>::poll
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/future/future.rs:125:9
  31: databend_query::servers::mysql::mysql_interactive_worker::InteractiveWorkerBase::exec_query::{{closure}}::{{closure}}::{{closure}}::{{closure}}
             at ./workspace/src/query/service/src/servers/mysql/mysql_interactive_worker.rs:399:76
  32: <minitrace::future::InSpan<T> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/minitrace-0.5.1/src/future.rs:121:19
  33: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:27
  34: async_backtrace::frame::Frame::in_scope::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:184:17
  35: std::thread::local::LocalKey<T>::try_with
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:270:16
  36: std::thread::local::LocalKey<T>::with
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/local.rs:246:9
  37: async_backtrace::frame::active_frame::with
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:81:9
  38: async_backtrace::frame::Frame::in_scope
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/frame.rs:180:13
  39: <async_backtrace::framed::Framed<F> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/async-backtrace-0.2.5/src/framed.rs:49:9
  40: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  41: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  42: tokio::runtime::task::core::Core<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  43: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  45: std::panicking::try::do_call
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  46: std::panicking::try
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  47: std::panic::catch_unwind
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  48: tokio::runtime::task::harness::poll_future
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  49: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  50: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  51: tokio::runtime::task::raw::RawTask::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  52: tokio::runtime::task::LocalNotified<S>::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  53: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
  54: tokio::runtime::coop::with_budget
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  55: tokio::runtime::coop::budget
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  56: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
  57: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  58: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  59: tokio::macros::scoped_tls::ScopedKey<T>::set
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  60: tokio::runtime::scheduler::multi_thread::worker::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  61: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:365:45
  62: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  63: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  64: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  65: tokio::runtime::task::core::Core<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  66: tokio::runtime::task::harness::poll_future::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  67: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  68: std::panicking::try::do_call
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  69: std::panicking::try
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  70: std::panic::catch_unwind
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  71: tokio::runtime::task::harness::poll_future
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  72: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  73: tokio::runtime::task::harness::Harness<T,S>::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  74: tokio::runtime::task::raw::RawTask::poll
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  75: tokio::runtime::task::UnownedTask<S>::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  76: tokio::runtime::blocking::pool::Task::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  77: tokio::runtime::blocking::pool::Inner::run
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  78: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at ./opt/rust/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
  79: std::sys_common::backtrace::__rust_begin_short_backtrace
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
  80: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
  81: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  82: std::panicking::try::do_call
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  83: std::panicking::try
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  84: std::panic::catch_unwind
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  85: std::thread::Builder::spawn_unchecked_::{{closure}}
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:528:30
  86: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  87: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  88: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  89: thread_start
             at ./rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
  90: <unknown>
  91: clone

```

**Comment by BohuTANG** [comment]
cc @zhyass

**Comment by dantengsky** [comment]
cc @lichuang

**Comment by zhyass** [comment]
```
mysql> create table t(a int, b int);
Query OK, 0 rows affected (0.04 sec)

mysql> insert into t values(1,2),(3,4);
Query OK, 2 rows affected (0.21 sec)

mysql> create table t2 as select * from t;
Query OK, 2 rows affected (0.35 sec)

mysql> show create table t2;
+-------+------------------------------------------------------------------+
| Table | Create Table                                                     |
+-------+------------------------------------------------------------------+
| t2    | CREATE TABLE `t2` (
  `a` INT NULL,
  `b` INT NULL
) ENGINE=FUSE |
+-------+------------------------------------------------------------------+
1 row in set (0.06 sec)
Read 0 rows, 0.00 B in 0.044 sec., 0 rows/sec., 0.00 B/sec.

mysql> alter table t2 add column c int;
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 463 panicked.

mysql> alter table t2 modify column b int64;
ERROR 1105 (HY000): TokioError. Code: 1068, Text = Cannot join handle from context's runtime, cause: task 536 panicked.
```
