### ISSUE TITLE
bug: merge into source query have a null value cause panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#13298]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.162-nightly

### What's Wrong?

merge into source query have a null value cause panic
```text
panicked at 'range 0..16 out of len 4', src/query/expression/src/values.rs:773:9
   0: common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: call<(&core::panic::panic_info::PanicInfo), (dyn core::ops::function::Fn<(&core::panic::panic_info::PanicInfo), Output=()> + core::marker::Send + core::marker::Sync), alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1999:9
   3: rust_panic_with_hook
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:709:13
   4: {closure#0}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:597:13
   5: __rust_end_short_backtrace<std::panicking::begin_panic_handler::{closure_env#0}, !>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:151:18
   6: begin_panic_handler
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:593:5
   7: panic_fmt
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panicking.rs:67:14
   8: common_expression::values::Column::slice
             at ./src/query/expression/src/values.rs:773:9
   9: common_expression::kernels::take::<impl common_expression::values::Column>::take
             at ./src/query/expression/src/kernels/take.rs:90:17
  10: common_expression::kernels::take::<impl common_expression::block::DataBlock>::take::{{closure}}
             at ./src/query/expression/src/kernels/take.rs:72:35
  11: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/adapters/map.rs:84:28
  12: core::iter::traits::iterator::Iterator::fold
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/traits/iterator.rs:2481:21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/adapters/map.rs:124:9
  14: core::iter::traits::iterator::Iterator::for_each
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/traits/iterator.rs:856:9
  15: alloc::vec::Vec<T,A>::extend_trusted
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/mod.rs:2827:17
  16: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/spec_extend.rs:26:9
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  18: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/spec_from_iter.rs:33:9
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/vec/mod.rs:2695:9
  20: core::iter::traits::iterator::Iterator::collect
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/iter/traits/iterator.rs:1895:9
  21: common_expression::kernels::take::<impl common_expression::block::DataBlock>::take
             at ./src/query/expression/src/kernels/take.rs:63:29
  22: databend_query::pipelines::processors::transforms::hash_join::probe_join::left_join::<impl databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState>::probe_left_join
             at ./src/query/service/src/pipelines/processors/transforms/hash_join/probe_join/left_join.rs:131:47
  23: databend_query::pipelines::processors::transforms::hash_join::result_blocks::<impl databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState>::result_blocks
             at ./src/query/service/src/pipelines/processors/transforms/hash_join/result_blocks.rs:149:21
  24: databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState::probe_join
             at ./src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs:243:9
  25: databend_query::pipelines::processors::transforms::hash_join::hash_join_probe_state::HashJoinProbeState::probe
             at ./src/query/service/src/pipelines/processors/transforms/hash_join/hash_join_probe_state.rs:154:33
  26: databend_query::pipelines::processors::transforms::hash_join::transform_hash_join_probe::TransformHashJoinProbe::probe
             at ./src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs:116:27
  27: <databend_query::pipelines::processors::transforms::hash_join::transform_hash_join_probe::TransformHashJoinProbe as common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/service/src/pipelines/processors/transforms/hash_join/transform_hash_join_probe.rs:368:21
  28: <alloc::boxed::Box<T> as common_pipeline_core::processors::processor::Processor>::process
             at ./src/query/pipeline/core/src/processors/processor.rs:169:9
  29: common_pipeline_core::processors::processor::ProcessorPtr::process
             at ./src/query/pipeline/core/src/processors/processor.rs:137:9
  30: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:82:9
  31: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task
             at ./src/query/service/src/pipelines/executor/executor_worker_context.rs:73:46
  32: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:376:45
  33: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:332:27
  34: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  35: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  36: __rust_try
  37: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  38: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  39: common_base::runtime::catch_unwind::catch_unwind
             at ./src/common/base/src/runtime/catch_unwind.rs:26:11
  40: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}
             at ./src/query/service/src/pipelines/executor/pipeline_executor.rs:331:34
  41: common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at ./src/common/base/src/runtime/thread.rs:85:21
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
  43: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  45: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  46: __rust_try
  47: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  48: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  49: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  50: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  51: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  52: thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
  53: <unknown>
  54: <unknown>
```

### How to Reproduce?

```sql
mysql> create table t11 (a int, b int);
Query OK, 0 rows affected (0.12 sec)

mysql> create table t12 (a int, b int);
Query OK, 0 rows affected (0.12 sec)

mysql> insert into t11 values (1, 10),(2, 20),(3, 30),(4, 40);
Query OK, 4 rows affected (0.12 sec)

mysql> insert into t12 values (1, 10),(2, 20),(3, 30),(4, 40);
Query OK, 4 rows affected (0.12 sec)

mysql> MERGE INTO t11 USING(SELECT NULL AS c0 FROM t12) AS t12 ON (t11.a OR TRUE) WHEN MATCHED AND TRUE THEN DELETE;
ERROR 1105 (HY000): PanicError. Code: 1104, Text = range 0..16 out of len 4.
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by JackTan25** [comment]
fixed by https://github.com/datafuselabs/databend/pull/13631, let's close it.
