### ISSUE TITLE
merge:  panicked at 'internal error: entered unreachable code: unable to push " \0\0\0\u{10}\0\0\u{5}OxMI8"

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#13367]
**Summary**

```
2023-10-20T22:27:36.415925Z  INFO databend_sqlsmith::runner: merge_sql: MERGE INTO t2 USING (SELECT t2.c14 AS cAeLun0 FROM t2) AS tdh43Q(cAeLun0) ON (FALSE XOR eq(FALSE, FALSE)) WHEN MATCHED AND noteq((FALSE,), (FALSE,)) THEN UPDATE SET c9 = $10, c22 = $23, c25 = c25, c28 = c28, c29 = c29, c31 = subtract_days(DATE_ADD(MINUTE, t2.c8, c13), []::Int64 NULL), c32 = c32 WHEN MATCHED AND c0 THEN UPDATE SET c0 = t2.c0 WHEN NOT MATCHED AND $1 THEN INSERT (c1, c6, c7, c9, c12, c14, c24, c29, c31, c36) VALUES(13, 22872, 1586268637, 115526.47474447405, 0.1786680552, to_timestamp(7351334683586), 18038, parse_json('["qmawe"]'), NULL, [(parse_json('[9355,true,"dRzeC","dZxWY"]'),)]) WHEN MATCHED AND and_filters(c0, c0) THEN UPDATE SET c20 = 21293, c21 = t2.$22 WHEN NOT MATCHED THEN INSERT VALUES(TRUE, 109, 59690, 4199489439, 12644013209214409949, 68, 7624, 1743511974, 5736329954979983771, -294137.1896449523, -9949716735.253986, 7463831.67, 0.0095998931, to_date(764666), to_timestamp(8268041083652), 'cLG7fNc', to_bitmap(398), parse_json('[true,false,22485,"HchX7",null]'), NULL, NULL, 43476, 2228780502, NULL, NULL, NULL, NULL, NULL, 163360.56745365262, 6065293965.832478, NULL, -0.0191259046, NULL, to_timestamp(8510882921771), NULL, to_bitmap(839), NULL, [(parse_json('[37248.80255705766,null,false,true]'),), (parse_json('{"ZXPda":53562.641408657524,"Zb3SK":"4LHL7","dNi81":null}'),)], [[-4252874.12, -20272397.61, -7775897.97], [-17897300.16, 6863815.55, 489613.44], [-16554236.93]])
panicked at 'internal error: entered unreachable code: unable to push " \0\0\0\u{10}\0\0\u{5}OxMI8" to Variant(StringColumnBuilder { need_estimated: true, data: [32, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0], offsets: [0, 8, 16] })', src/query/expression/src/values.rs:2192:34
   0: common_tracing::panic_hook::log_panic
             at /workspace/src/common/tracing/src/panic_hook.rs:35:21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at /workspace/src/common/tracing/src/panic_hook.rs:30:9
  26: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:464:19
  27: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  28: common_base::runtime::catch_unwind::catch_unwind
             at /workspace/src/common/base/src/runtime/catch_unwind.rs:26:11
  29: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}
             at /workspace/src/query/service/src/pipelines/executor/pipeline_executor.rs:331:34
  30: common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at /workspace/src/common/base/src/runtime/thread.rs:85:21
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys_common/backtrace.rs:135:18
  32: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:529:17
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/panic/unwind_safe.rs:271:9
  34: std::panicking::try::do_call
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:500:40
  35: std::panicking::try
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panicking.rs:[464](https://github.com/datafuselabs/databend/actions/runs/6593110776/job/17915513311#step:4:465):19
  36: std::panic::catch_unwind
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/panic.rs:142:14
  37: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/thread/mod.rs:528:30
  38: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/core/src/ops/function.rs:250:5
  39: call_once<(), dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  40: call_once<(), alloc::boxed::Box<dyn core::ops::function::FnOnce<(), Output=()>, alloc::alloc::Global>, alloc::alloc::Global>
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/alloc/src/boxed.rs:1985:9
  41: thread_start
             at /rustc/8b35c0bb0f833c0077dc57006eb317edde2a2d1e/library/std/src/sys/unix/thread.rs:108:17
  42: <unknown>
  43: <unknown>
```

https://github.com/datafuselabs/databend/actions/runs/6593110776/job/17915513311#step:4:396

**Comment by BohuTANG** [comment]
```
panicked at 'internal error: entered unreachable code: unable to push " \0\0\0\u{10}\0\0\u{5}OxMI8" to Variant(StringColumnBuilder { need_estimated: true, data: [32, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0], offsets: [0, 8, 16] })', src/query/expression/src/values.rs:2192:34
```

It seems the bug of values builder.
cc @b41sh

**Comment by BohuTANG** [comment]
Another issue looks same at:
```
2023-10-20T22:27:36.507095Z  INFO databend_sqlsmith::runner: merge_sql: MERGE INTO t4 USING (SELECT NULL AS cTWLTe0, NULL AS cTWLTe1, TRUE AS cTWLTe2, FALSE AS cTWLTe3 FROM t1) AS tTWK9z(cTWLTe0, cTWLTe1, cTWLTe2, cTWLTe3) ON (FALSE XOR gte(52125, c2)) WHEN MATCHED AND TRUE THEN UPDATE SET c4 = c4, c5 = to_int8(c2), c9 = c9, c21 = t4.$22, c30 = NULL, c35 = c35 WHEN MATCHED AND t4.c0 THEN UPDATE SET c36 = c36 WHEN NOT MATCHED THEN INSERT VALUES(FALSE, 58, 59391, 2483666243, 5327155928494843132, 79, 15334, 721645828, 441204698635459555, 337826.2984116087, 15619135212.063, 13256165.48, -0.0509381445, to_date(305363), to_timestamp(9218113958700), '16rFB9x', to_bitmap(588), parse_json('[]'), NULL, 63, 9150, 4204678868, 11729008221587433423, NULL, 27693, NULL, NULL, 200260.25611359824, -3994480044.5874577, NULL, NULL, to_date(428978), NULL, '6kQjMwb', to_bitmap(596), NULL, [['QXN3Vuz', 'S6TVmXj', 'nJ1ffzt'], ['hGZmw4u', 'wkLZmYE'], ['eDEwcp4', 'FXgUKLe']], {'fHoJlHq':[{'uJzbWpN':22843,'fK84EhA':50410,'4IKETEP':38485}, {'Kwfkm8z':34656}, {'ZRlKIIt':15116}],'GQ4VVHV':[{'FY7W2Mz':44544,'IvApXxx':51162}],'3cVkKsa':[{'B4lN4z8':4366,'51KF35A':6518,'gEGFTW1':12946}, {'0KsAbAY':37371,'dgjLu0B':35457,'hzouCWA':42764}]})
panicked at 'range 0..100 out of len 10', src/query/expression/src/values.rs:777:9
```

https://github.com/datafuselabs/databend/actions/runs/6593110776/job/17915513311#step:4:486
