### ISSUE TITLE
bug: read_only attached tables of storage format `native` do not work as expected

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/databend#13720]
**Summary**

for tables created with storage format `Naitve`, e.g.

CREATE TABLE
  `lineitem` 's3://test_bucket/' CONNECTION = (
    ACCESS_KEY_ID = 'xxxx',
    SECRET_ACCESS_KEY = 'xxx',
    ENDPOINT_URL = 'https://xxx/'
  ) **STORAGE_FORMAT = 'native'** AS
SELECT
  *
FROM
  tpch_sf100.lineitem;
  
 -------------
  
if  they were read_only attached, e.g.

ATTACH TABLE lineitem 's3://xxx/6826433/6826522/' CONNECTION = (
       AWS_KEY_ID = 'xxx',
      AWS_SECRET_KEY = 'xxx',
      ENDPOINT_URL = 'https://xxx/'
     ) **READ_ONLY**;

-----

Queries of read_only attached table (e.g. `select * from lineitem limit 1`) panics:

~~~
panicked at src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:196](http://block_reader_parquet_deserialize.rs:196/):46:
called `Option::unwrap()` on a `None` value
   0: common_tracing::panic_hook::log_panic
             at /workspace/src/common/tracing/src/[panic_hook.rs:35](http://panic_hook.rs:35/):21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at /workspace/src/common/tracing/src/[panic_hook.rs:30](http://panic_hook.rs:30/):9
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/[boxed.rs:2021](http://boxed.rs:2021/):9
   3: std::panicking::rust_panic_with_hook
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:735](http://panicking.rs:735/):13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:601](http://panicking.rs:601/):13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys_common/[backtrace.rs:170](http://backtrace.rs:170/):18
   6: rust_begin_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:597](http://panicking.rs:597/):5
   7: core::panicking::panic_fmt
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[panicking.rs:72](http://panicking.rs:72/):14
   8: core::panicking::panic
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[panicking.rs:127](http://panicking.rs:127/):5
   9: core::option::Option<T>::unwrap
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[option.rs:925](http://option.rs:925/):21
  10: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::chunks_to_parquet_array_iter::{{closure}}
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:196](http://block_reader_parquet_deserialize.rs:196/):28
  11: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[map.rs:91](http://map.rs:91/):28
  12: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2461](http://iterator.rs:2461/):21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[map.rs:117](http://map.rs:117/):9
  14: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[mod.rs:199](http://mod.rs:199/):9
  15: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2523](http://iterator.rs:2523/):9
  16: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[mod.rs:182](http://mod.rs:182/):14
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/vec/[spec_from_iter_nested.rs:26](http://spec_from_iter_nested.rs:26/):32
  18: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/vec/[spec_from_iter.rs:33](http://spec_from_iter.rs:33/):9
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/vec/[mod.rs:2750](http://mod.rs:2750/):9
  20: core::iter::traits::iterator::Iterator::collect
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2053](http://iterator.rs:2053/):9
  21: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[result.rs:1934](http://result.rs:1934/):51
  22: core::iter::adapters::try_process
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[mod.rs:168](http://mod.rs:168/):17
  23: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[result.rs:1934](http://result.rs:1934/):9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2053](http://iterator.rs:2053/):9
  25: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::chunks_to_parquet_array_iter
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:192](http://block_reader_parquet_deserialize.rs:192/):23
  26: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_field
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:293](http://block_reader_parquet_deserialize.rs:293/):34
  27: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_parquet_chunks_with_buffer
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:114](http://block_reader_parquet_deserialize.rs:114/):19
  28: <common_storages_fuse::operations::read::parquet_data_source_deserializer::DeserializeDataTransform as common_pipeline_core::processors::processor::Processor>::process
             at /workspace/src/query/storages/fuse/src/operations/read/[parquet_data_source_deserializer.rs:196](http://parquet_data_source_deserializer.rs:196/):42
  29: <alloc::boxed::Box<T> as common_pipeline_core::processors::processor::Processor>::process
             at /workspace/src/query/pipeline/core/src/processors/[processor.rs:196](http://processor.rs:196/):9
  30: common_pipeline_core::processors::processor::ProcessorPtr::process
             at /workspace/src/query/pipeline/core/src/processors/[processor.rs:152](http://processor.rs:152/):9
  31: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task
             at /workspace/src/query/service/src/pipelines/executor/[executor_worker_context.rs:98](http://executor_worker_context.rs:98/):17
  32: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task
             at /workspace/src/query/service/src/pipelines/executor/[executor_worker_context.rs:78](http://executor_worker_context.rs:78/):46
  33: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread
             at /workspace/src/query/service/src/pipelines/executor/[pipeline_executor.rs:415](http://pipeline_executor.rs:415/):21
  34: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}
             at /workspace/src/query/service/src/pipelines/executor/[pipeline_executor.rs:364](http://pipeline_executor.rs:364/):34
  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9
  36: std::panicking::try::do_call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:504](http://panicking.rs:504/):40
  37: std::panicking::try
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:468](http://panicking.rs:468/):19
  38: std::panic::catch_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panic.rs:142](http://panic.rs:142/):14
  39: common_base::runtime::catch_unwind::catch_unwind
             at /workspace/src/common/base/src/runtime/[catch_unwind.rs:26](http://catch_unwind.rs:26/):11
  40: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}
             at /workspace/src/query/service/src/pipelines/executor/[pipeline_executor.rs:361](http://pipeline_executor.rs:361/):34
  41: common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at /workspace/src/common/base/src/runtime/[thread.rs:85](http://thread.rs:85/):21
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys_common/[backtrace.rs:154](http://backtrace.rs:154/):18
  43: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/thread/[mod.rs:529](http://mod.rs:529/):17
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9
  45: std::panicking::try::do_call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:504](http://panicking.rs:504/):40
  46: std::panicking::try
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:468](http://panicking.rs:468/):19
  47: std::panic::catch_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panic.rs:142](http://panic.rs:142/):14
  48: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/thread/[mod.rs:528](http://mod.rs:528/):30
  49: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/ops/[function.rs:250](http://function.rs:250/):5
  50: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/[boxed.rs:2007](http://boxed.rs:2007/):9
  51: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/[boxed.rs:2007](http://boxed.rs:2007/):9
  52: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys/unix/[thread.rs:108](http://thread.rs:108/):17
  53: start_thread
             at ./nptl/pthread_create.c:442:8
  54: clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

panicked at src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:196](http://block_reader_parquet_deserialize.rs:196/):46:
called `Option::unwrap()` on a `None` value
   0: common_tracing::panic_hook::log_panic
             at /workspace/src/common/tracing/src/[panic_hook.rs:35](http://panic_hook.rs:35/):21
   1: common_tracing::panic_hook::set_panic_hook::{{closure}}
             at /workspace/src/common/tracing/src/[panic_hook.rs:30](http://panic_hook.rs:30/):9
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/[boxed.rs:2021](http://boxed.rs:2021/):9
   3: std::panicking::rust_panic_with_hook
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:735](http://panicking.rs:735/):13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:601](http://panicking.rs:601/):13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys_common/[backtrace.rs:170](http://backtrace.rs:170/):18
   6: rust_begin_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:597](http://panicking.rs:597/):5
   7: core::panicking::panic_fmt
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[panicking.rs:72](http://panicking.rs:72/):14
   8: core::panicking::panic
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[panicking.rs:127](http://panicking.rs:127/):5
   9: core::option::Option<T>::unwrap
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[option.rs:925](http://option.rs:925/):21
  10: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::chunks_to_parquet_array_iter::{{closure}}
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:196](http://block_reader_parquet_deserialize.rs:196/):28
  11: core::iter::adapters::map::map_try_fold::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[map.rs:91](http://map.rs:91/):28
  12: core::iter::traits::iterator::Iterator::try_fold
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2461](http://iterator.rs:2461/):21
  13: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[map.rs:117](http://map.rs:117/):9
  14: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::try_fold
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[mod.rs:199](http://mod.rs:199/):9
  15: core::iter::traits::iterator::Iterator::try_for_each
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2523](http://iterator.rs:2523/):9
  16: <core::iter::adapters::GenericShunt<I,R> as core::iter::traits::iterator::Iterator>::next
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[mod.rs:182](http://mod.rs:182/):14
  17: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/vec/[spec_from_iter_nested.rs:26](http://spec_from_iter_nested.rs:26/):32
  18: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/vec/[spec_from_iter.rs:33](http://spec_from_iter.rs:33/):9
  19: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/alloc/src/vec/[mod.rs:2750](http://mod.rs:2750/):9
  20: core::iter::traits::iterator::Iterator::collect
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2053](http://iterator.rs:2053/):9
  21: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[result.rs:1934](http://result.rs:1934/):51
  22: core::iter::adapters::try_process
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/adapters/[mod.rs:168](http://mod.rs:168/):17
  23: <core::result::Result<V,E> as core::iter::traits::collect::FromIterator<core::result::Result<A,E>>>::from_iter
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/[result.rs:1934](http://result.rs:1934/):9
  24: core::iter::traits::iterator::Iterator::collect
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/iter/traits/[iterator.rs:2053](http://iterator.rs:2053/):9
  25: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::chunks_to_parquet_array_iter
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:192](http://block_reader_parquet_deserialize.rs:192/):23
  26: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_field
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:293](http://block_reader_parquet_deserialize.rs:293/):34
  27: common_storages_fuse::io::read::block::block_reader_parquet_deserialize::<impl common_storages_fuse::io::read::block::block_reader::BlockReader>::deserialize_parquet_chunks_with_buffer
             at /workspace/src/query/storages/fuse/src/io/read/block/[block_reader_parquet_deserialize.rs:114](http://block_reader_parquet_deserialize.rs:114/):19
  28: <common_storages_fuse::operations::read::parquet_data_source_deserializer::DeserializeDataTransform as common_pipeline_core::processors::processor::Processor>::process
             at /workspace/src/query/storages/fuse/src/operations/read/[parquet_data_source_deserializer.rs:196](http://parquet_data_source_deserializer.rs:196/):42
  29: <alloc::boxed::Box<T> as common_pipeline_core::processors::processor::Processor>::process
             at /workspace/src/query/pipeline/core/src/processors/[processor.rs:196](http://processor.rs:196/):9
  30: common_pipeline_core::processors::processor::ProcessorPtr::process
             at /workspace/src/query/pipeline/core/src/processors/[processor.rs:152](http://processor.rs:152/):9
  31: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task
             at /workspace/src/query/service/src/pipelines/executor/[executor_worker_context.rs:98](http://executor_worker_context.rs:98/):17
  32: databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task
             at /workspace/src/query/service/src/pipelines/executor/[executor_worker_context.rs:78](http://executor_worker_context.rs:78/):46
  33: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread
             at /workspace/src/query/service/src/pipelines/executor/[pipeline_executor.rs:415](http://pipeline_executor.rs:415/):21
  34: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}
             at /workspace/src/query/service/src/pipelines/executor/[pipeline_executor.rs:364](http://pipeline_executor.rs:364/):34
  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9
  36: std::panicking::try::do_call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:504](http://panicking.rs:504/):40
  37: std::panicking::try
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:468](http://panicking.rs:468/):19
  38: std::panic::catch_unwind
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panic.rs:142](http://panic.rs:142/):14
  39: common_base::runtime::catch_unwind::catch_unwind
             at /workspace/src/common/base/src/runtime/[catch_unwind.rs:26](http://catch_unwind.rs:26/):11
  40: databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}
             at /workspace/src/query/service/src/pipelines/executor/[pipeline_executor.rs:361](http://pipeline_executor.rs:361/):34
  41: common_base::runtime::thread::Thread::named_spawn::{{closure}}
             at /workspace/src/common/base/src/runtime/[thread.rs:85](http://thread.rs:85/):21
  42: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/sys_common/[backtrace.rs:154](http://backtrace.rs:154/):18
  43: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/thread/[mod.rs:529](http://mod.rs:529/):17
  44: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/core/src/panic/[unwind_safe.rs:271](http://unwind_safe.rs:271/):9
  45: std::panicking::try::do_call
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:504](http://panicking.rs:504/):40
  46: std::panicking::try
             at /rustc/54b0434cead71e33bb4ddb52acde7767452b276d/library/std/src/[panicking.rs:468](http://panicking.rs:468/):19
~~~

**Comment by sundy-li** [comment]
goes into block_reader_parquet_deserialize , may be we lost the storage format in attach table.

**Comment by dantengsky** [comment]
> goes into block_reader_parquet_deserialize , may be we lost the storage format in attach table.

yes, during attaching that target table, the storage format was not correctly fetched and kept.

unfortunately, `storage_format` is persistent in the meta server, and during attaching, the "original" meta server is not accessible.

maybe we should also store the table options in the table snapshot hint file as well, so that, later when attaching the target table, those options could be obtained by merely reading data from object storage.

**Comment by dantengsky** [comment]
I'll try to address this problem later.
