### ISSUE TITLE
bug: cast big integer to decimal cause panic

### ISSUE THREAD

**Issue by b41sh** [datafuselabs/databend#14469]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

v1.2.314-nightly

### What's Wrong?

cast big integer to decimal cause panic
```
panicked at /home/b41sh/.cargo/git/checkouts/ethnum-rs-726d471e50d0bee8/4cb05f1/src/int/ops.rs:17:1:
attempt to multiply with overflow
   0: databend_common_tracing::panic_hook::log_panic
             at ./src/common/tracing/src/panic_hook.rs:35:21
   1: databend_common_tracing::panic_hook::set_panic_hook::{{closure}}
             at ./src/common/tracing/src/panic_hook.rs:30:9
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/alloc/src/boxed.rs:2030:9
   3: std::panicking::rust_panic_with_hook
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:785:13
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:651:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/sys_common/backtrace.rs:171:18
   6: rust_begin_unwind
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/std/src/panicking.rs:647:5
   7: core::panicking::panic_fmt
             at /rustc/d5fd0997291ca0135401a39dff25c8a9c13b8961/library/core/src/panicking.rs:72:14
   8: ethnum::int::ops::<impl core::ops::arith::Mul for &ethnum::int::I256>::mul
             at /home/b41sh/.cargo/git/checkouts/ethnum-rs-726d471e50d0bee8/4cb05f1/src/macros/ops.rs:167:25
   9: ethnum::int::ops::<impl core::ops::arith::Mul for ethnum::int::I256>::mul
             at /home/b41sh/.cargo/git/checkouts/ethnum-rs-726d471e50d0bee8/4cb05f1/src/int/ops.rs:17:1
  10: databend_common_functions::scalars::decimal::cast::integer_to_decimal::{{closure}}
             at ./src/query/functions/src/scalars/decimal/cast.rs:503:17
  11: databend_common_expression::register::vectorize_with_builder_1_arg::{{closure}}
             at ./src/query/expression/src/register.rs:2195:17
  12: databend_common_functions::scalars::decimal::cast::integer_to_decimal
             at ./src/query/functions/src/scalars/decimal/cast.rs:516:5
  13: databend_common_functions::scalars::decimal::cast::convert_to_decimal
             at ./src/query/functions/src/scalars/decimal/cast.rs:341:5
  14: databend_common_functions::scalars::decimal::cast::convert_to_decimal_domain
             at ./src/query/functions/src/scalars/decimal/cast.rs:441:15
  15: databend_common_functions::scalars::decimal::cast::register_to_decimal::{{closure}}::{{closure}}
             at ./src/query/functions/src/scalars/decimal/cast.rs:78:21
```

### How to Reproduce?

```sql
mysql> select CAST(17548423738721552635 AS Decimal(69, 63));
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    17
Current database: default
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by guojidan** [comment]
I will try to fix this bug

**Comment by guojidan** [comment]
This doesn't seem like a bug, Just overflow the precision of Decimal(69, 63), I think we just need change the panic to error prompt?

**Comment by b41sh** [comment]
> This doesn't seem like a bug, Just overflow the precision of Decimal(69, 63), I think we just need change the panic to error prompt?

yes, we should return overflow error instead of panic.
