### ISSUE TITLE
Flaky test: query/src/datasources/table/fuse/io/block_reader_test.rs:67:5

### ISSUE THREAD

**Issue by drmingdrmer** [datafuselabs/databend#2416]
https://github.com/datafuselabs/databend/runs/3989411389?check_suite_focus=true

```
thread 'datasources::table::fuse::io::block_reader_test::test_block_reader_read' panicked at 'assertion failed: got.is_ok()', query/src/datasources/table/fuse/io/block_reader_test.rs:67:5
stack backtrace:
   0:        0x116fd3641 - std::backtrace_rs::backtrace::libunwind::trace::hbebac83a7f69c4c2
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x116fd3641 - std::backtrace_rs::backtrace::trace_unsynchronized::h70204c1920f029d2
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x116fd3641 - std::sys_common::backtrace::_print_fmt::he9f032d543410c72
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x116fd3641 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4e8c7f30caf14f6b
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x11702423b - core::fmt::write::h6f39ff4b18ec6aa7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/fmt/mod.rs:1125:17
   5:        0x116fc4eda - std::io::Write::write_fmt::h83346480ffdbbe85
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/io/mod.rs:1667:15
   6:        0x116fd6a65 - std::sys_common::backtrace::_print::hd174081a00e4492d
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x116fd6a65 - std::sys_common::backtrace::print::h34ed55d4c4c57d09
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x116fd6a65 - std::panicking::default_hook::{{closure}}::h409faa78641a7645
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:210:50
   9:        0x116fd667f - std::panicking::default_hook::h7ee7aa30ab262721
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:224:9
  10:        0x116fd7280 - std::panicking::rust_panic_with_hook::h5c4d3dad4cf39db7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:624:17
  11:        0x116fd6cf4 - std::panicking::begin_panic_handler::{{closure}}::hbf5ff5e8c653ab15
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:519:13
  12:        0x116fd3ab7 - std::sys_common::backtrace::__rust_end_short_backtrace::h8ba5e37c718cb8e4
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x116fd6c8a - rust_begin_unwind
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:517:5
  14:        0x11717dfcf - core::panicking::panic_fmt::h6c191e7f85e62838
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panicking.rs:96:14
  15:        0x11717df27 - core::panicking::panic::hf0752d57e0382e6d
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panicking.rs:50:5
  16:        0x10939c7c1 - databend_query::datasources::table::fuse::io::block_reader_test::test_block_reader_read::{{closure}}::hf5c2d69ab570851a
                               at /Users/runner/work/databend/databend/query/src/datasources/table/fuse/io/block_reader_test.rs:67:5
```

**Comment by dantengsky** [comment]
seems pr #2581 resolved this, pls feel free to reopen this if necessary
