### ISSUE TITLE
[flaky test]   'datasources::table::fuse::io::block_reader_test::test_block_reader_read' panicked at 'Err(Code: 24, displayText = External error: Invalid Parquet file. Size is smaller than footer.

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#2579]
**Summary**

```
failures:

---- datasources::table::fuse::io::block_reader_test::test_block_reader_read stdout ----
thread 'datasources::table::fuse::io::block_reader_test::test_block_reader_read' panicked at 'Err(Code: 24, displayText = External error: Invalid Parquet file. Size is smaller than footer.

   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.62/src/backtrace/libunwind.rs:93:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.62/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.62/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.62/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.62/src/capture.rs:140:22
   4: common_exception::exception::ErrorCode::ParquetError
             at /Users/runner/work/databend/databend/common/exception/src/exception.rs:110:77
   5: databend_query::datasources::table::fuse::io::block_reader::do_read::{{closure}}::{{closure}}
             at src/datasources/table/fuse/io/block_reader.rs:73:22
      core::result::Result<T,E>::map_err
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/result.rs:853:27
   6: databend_query::datasources::table::fuse::io::block_reader::do_read::{{closure}}
             at src/datasources/table/fuse/io/block_reader.rs:71:20
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/future/mod.rs:80:19
   8: databend_query::datasources::table::fuse::io::block_reader_test::test_block_reader_read::{{closure}}
             at src/datasources/table/fuse/io/block_reader_test.rs:66:15
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/future/mod.rs:80:19
  10: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:54
      tokio::coop::with_budget::{{closure}}
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:106:9
  11: std::thread::local::LocalKey<T>::try_with
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/local.rs:399:16
  12: std::thread::local::LocalKey<T>::with
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/local.rs:375:9
  13: tokio::coop::with_budget
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:99:5
      tokio::coop::budget
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:76:5
      tokio::park::thread::CachedParkThread::block_on
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:31
  14: tokio::runtime::enter::Enter::block_on
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/enter.rs:151:13
  15: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/mod.rs:77:9
  16: tokio::runtime::Runtime::block_on
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/mod.rs:463:43
  17: databend_query::datasources::table::fuse::io::block_reader_test::test_block_reader_read
             at src/datasources/table/fuse/io/block_reader_test.rs:73:5
  18: databend_query::datasources::table::fuse::io::block_reader_test::test_block_reader_read::{{closure}}
             at src/datasources/table/fuse/io/block_reader_test.rs:49:7
      core::ops::function::FnOnce::call_once
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/ops/function.rs:227:5
  19: core::ops::function::FnOnce::call_once
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/ops/function.rs:227:5
      test::__rust_begin_short_backtrace
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:578:5
  20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panic.rs:129:14
      test::run_test_in_process
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:601:18
      test::run_test::run_test_inner::{{closure}}
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:493:39
  21: test::run_test::run_test_inner::{{closure}}
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:520:37
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:125:18
  22: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/mod.rs:481:17
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panic/unwind_safe.rs:271:9
      std::panicking::try::do_call
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:403:40
      std::panicking::try
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:367:19
      std::panic::catch_unwind
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panic.rs:129:14
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/mod.rs:480:30
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/ops/function.rs:227:5
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys/unix/thread.rs:106:17
  24: __pthread_start
)', query/src/datasources/table/fuse/io/block_reader_test.rs:67:5
stack backtrace:
   0:        0x10fe96471 - std::backtrace_rs::backtrace::libunwind::trace::hbebac83a7f69c4c2
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x10fe96471 - std::backtrace_rs::backtrace::trace_unsynchronized::h70204c1920f029d2
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x10fe96471 - std::sys_common::backtrace::_print_fmt::he9f032d543410c72
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x10fe96471 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4e8c7f30caf14f6b
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x10fee706b - core::fmt::write::h6f39ff4b18ec6aa7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/fmt/mod.rs:1125:17
   5:        0x10fe87d0a - std::io::Write::write_fmt::h83346480ffdbbe85
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/io/mod.rs:1667:15
   6:        0x10fe99895 - std::sys_common::backtrace::_print::hd174081a00e4492d
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x10fe99895 - std::sys_common::backtrace::print::h34ed55d4c4c57d09
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x10fe99895 - std::panicking::default_hook::{{closure}}::h409faa78641a7645
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:210:50
   9:        0x10fe994af - std::panicking::default_hook::h7ee7aa30ab262721
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:224:9
  10:        0x10fe9a0b0 - std::panicking::rust_panic_with_hook::h5c4d3dad4cf39db7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:624:17
  11:        0x10fe99b4e - std::panicking::begin_panic_handler::{{closure}}::hbf5ff5e8c653ab15
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:521:13
  12:        0x10fe968e7 - std::sys_common::backtrace::__rust_end_short_backtrace::h8ba5e37c718cb8e4
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:141:18
  13:        0x10fe99aba - rust_begin_unwind
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:517:5
  14:        0x11003ffaf - core::panicking::panic_fmt::h6c191e7f85e62838
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panicking.rs:96:14
  15:        0x1021b5db3 - databend_query::datasources::table::fuse::io::block_reader_test::test_block_reader_read::{{closure}}::hfb9990c9b0f8fdc9
                               at /Users/runner/work/databend/databend/query/src/datasources/table/fuse/io/block_reader_test.rs:67:5
  16:        0x101d13aa7 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha49197cae39f19d5
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/future/mod.rs:80:19
  17:        0x10144fc83 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::hd19c903feabab1d4
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:54
  18:        0x10144fc83 - tokio::coop::with_budget::{{closure}}::hb793e9e8321d6664
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:106:9
  19:        0x100bd8d88 - std::thread::local::LocalKey<T>::try_with::h0587e638d35567e5
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/local.rs:399:16
  20:        0x100bc0676 - std::thread::local::LocalKey<T>::with::h32f4e02d9050cca3
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/local.rs:375:9
  21:        0x10148860a - tokio::coop::with_budget::h1edede3cb27f722c
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:99:5
  22:        0x10148860a - tokio::coop::budget::hef8953890a837f37
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/coop.rs:76:5
  23:        0x10148860a - tokio::park::thread::CachedParkThread::block_on::h36327d7165c94af3
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/park/thread.rs:263:31
  24:        0x101750182 - tokio::runtime::enter::Enter::block_on::h0552078db89dc00d
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/enter.rs:151:13
  25:        0x1014f1427 - tokio::runtime::thread_pool::ThreadPool::block_on::h1a44c8c5696b02ae
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/thread_pool/mod.rs:77:9
  26:        0x10175d475 - tokio::runtime::Runtime::block_on::h09fcf73fb1adbdef
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.13.0/src/runtime/mod.rs:463:43
  27:        0x1021b44c6 - databend_query::datasources::table::fuse::io::block_reader_test::test_block_reader_read::h7e460291f005cd65
                               at /Users/runner/work/databend/databend/query/src/datasources/table/fuse/io/block_reader_test.rs:73:5
  28:        0x100d6497a - databend_query::datasources::table::fuse::io::block_reader_test::test_block_reader_read::{{closure}}::h0eb4241b83bcc399
                               at /Users/runner/work/databend/databend/query/src/datasources/table/fuse/io/block_reader_test.rs:49:7
  29:        0x100d6497a - core::ops::function::FnOnce::call_once::h996521fa69ccc401
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/ops/function.rs:227:5
  30:        0x1029149d6 - core::ops::function::FnOnce::call_once::h23b28e3d330f1043
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/ops/function.rs:227:5
  31:        0x1029149d6 - test::__rust_begin_short_backtrace::hf0bab4aabe7ca6ab
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:578:5
  32:        0x102913689 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h791dabc846de034c
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
  33:        0x102913689 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8b77bee7a5100cbb
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panic/unwind_safe.rs:271:9
  34:        0x102913689 - std::panicking::try::do_call::h1cbd8986472768a9
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:403:40
  35:        0x102913689 - std::panicking::try::ha52af2bd6590eb12
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:367:19
  36:        0x102913689 - std::panic::catch_unwind::hb812fbc397b33c74
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panic.rs:129:14
  37:        0x102913689 - test::run_test_in_process::h7d49ba8692ea72f1
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:601:18
  38:        0x102913689 - test::run_test::run_test_inner::{{closure}}::h9627291089c4a8fa
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:493:39
  39:        0x1028de5eb - test::run_test::run_test_inner::{{closure}}::he789fded498c37b9
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:520:37
  40:        0x1028de5eb - std::sys_common::backtrace::__rust_begin_short_backtrace::h8cb5a355420cadb4
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:125:18
  41:        0x1028e3de4 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hd702d16924ef960c
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/mod.rs:481:17
  42:        0x1028e3de4 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6d55131e60e0b831
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panic/unwind_safe.rs:271:9
  43:        0x1028e3de4 - std::panicking::try::do_call::hc902afa168848831
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:403:40
  44:        0x1028e3de4 - std::panicking::try::hfb85629ebb6b5ed3
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:367:19
  45:        0x1028e3de4 - std::panic::catch_unwind::hdb3b9bca8eaeff84
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panic.rs:129:14
  46:        0x1028e3de4 - std::thread::Builder::spawn_unchecked::{{closure}}::h73744e01e0024aaa
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/mod.rs:480:30
  47:        0x1028e3de4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e608be3e4641a17
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/ops/function.rs:227:5
  48:        0x10fea5547 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2e62e35cae6104e7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
  49:        0x10fea5547 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hac32246a2fa5b299
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
  50:        0x10fea5547 - std::sys::unix::thread::Thread::new::thread_start::hb175ba9892561b14
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys/unix/thread.rs:106:17
  51:     0x7fff6c969109 - __pthread_start


failures:
    datasources::table::fuse::io::block_reader_test::test_block_reader_read

test result: FAILED. 144 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 20.74s
```

**Comment by dantengsky** [comment]
got it， already have some clues

**Comment by dantengsky** [comment]
tracking related issues:

- issue #2416
- issue #2468
