### ISSUE TITLE
 flight::metasrv_flight_kv_api::test_kv_api_timeout stdout always failed on MacOS 

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3103]
**Summary**

```
failures:

---- flight::metasrv_flight_kv_api::test_kv_api_timeout stdout ----
thread 'flight::metasrv_flight_kv_api::test_kv_api_timeout' panicked at 'assertion failed: `(left == right)`
  left: `[None, None]`,
 right: `[None, Some(SeqV { seq: 3, meta: Some(KVMeta { expire_at: Some(1637890775) }), data: [118, 50] })]`', /Users/runner/work/databend/databend/common/meta/api/src/kv_api_test_suite.rs:308:13
stack backtrace:
   0:        0x118189fd1 - std::backtrace_rs::backtrace::libunwind::trace::hbebac83a7f69c4c2
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:        0x118189fd1 - std::backtrace_rs::backtrace::trace_unsynchronized::h70204c1920f029d2
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x118189fd1 - std::sys_common::backtrace::_print_fmt::he9f032d543410c72
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:67:5
   3:        0x118189fd1 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4e8c7f30caf14f6b
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:46:22
   4:        0x1181dabcb - core::fmt::write::h6f39ff4b18ec6aa7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/fmt/mod.rs:1125:17
   5:        0x11817b86a - std::io::Write::write_fmt::h83346480ffdbbe85
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/io/mod.rs:1667:15
   6:        0x11818d3f5 - std::sys_common::backtrace::_print::hd174081a00e4492d
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:49:5
   7:        0x11818d3f5 - std::sys_common::backtrace::print::h34ed55d4c4c57d09
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:36:9
   8:        0x11818d3f5 - std::panicking::default_hook::{{closure}}::h409faa78641a7645
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:210:50
   9:        0x11818d00f - std::panicking::default_hook::h7ee7aa30ab262721
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:224:9
  10:        0x11818dc10 - std::panicking::rust_panic_with_hook::h5c4d3dad4cf39db7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:624:17
  11:        0x11818d6ae - std::panicking::begin_panic_handler::{{closure}}::hbf5ff5e8c653ab15
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:521:13
  12:        0x11818a447 - std::sys_common::backtrace::__rust_end_short_backtrace::h8ba5e37c718cb8e4
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panic/unwind_safe.rs:271:9
  38:        0x10e21cee9 - std::panicking::try::do_call::h1cbd8986472768a9
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:403:40
  39:        0x10e21cee9 - std::panicking::try::ha52af2bd6590eb12
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:367:19
  40:        0x10e21cee9 - std::panic::catch_unwind::hb812fbc397b33c74
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panic.rs:129:14
  41:        0x10e21cee9 - test::run_test_in_process::h7d49ba8692ea72f1
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:601:18
  42:        0x10e21cee9 - test::run_test::run_test_inner::{{closure}}::h9627291089c4a8fa
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:493:39
  43:        0x10e1e7e4b - test::run_test::run_test_inner::{{closure}}::he789fded498c37b9
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/test/src/lib.rs:520:37
  44:        0x10e1e7e4b - std::sys_common::backtrace::__rust_begin_short_backtrace::h8cb5a355420cadb4
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys_common/backtrace.rs:125:18
  45:        0x10e1ed644 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hd702d16924ef960c
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/mod.rs:481:17
  46:        0x10e1ed644 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h6d55131e60e0b831
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/panic/unwind_safe.rs:271:9
  47:        0x10e1ed644 - std::panicking::try::do_call::hc902afa168848831
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:403:40
  48:        0x10e1ed644 - std::panicking::try::hfb85629ebb6b5ed3
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panicking.rs:367:19
  49:        0x10e1ed644 - std::panic::catch_unwind::hdb3b9bca8eaeff84
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/panic.rs:129:14
  50:        0x10e1ed644 - std::thread::Builder::spawn_unchecked::{{closure}}::h73744e01e0024aaa
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/thread/mod.rs:480:30
  51:        0x10e1ed644 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0e608be3e4641a17
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/core/src/ops/function.rs:227:5
  52:        0x1181990a7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2e62e35cae6104e7
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
  53:        0x1181990a7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hac32246a2fa5b299
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/alloc/src/boxed.rs:1636:9
  54:        0x1181990a7 - std::sys::unix::thread::Thread::new::thread_start::hb175ba9892561b14
                               at /rustc/b69fe57261086e70aea9d5b58819a1794bf7c121/library/std/src/sys/unix/thread.rs:106:17
  55:     0x7fff6ecff109 - __pthread_start


failures:
    flight::metasrv_flight_kv_api::test_kv_api_timeout
```

**Comment by BohuTANG** [comment]
Same issue happens here:
https://github.com/datafuselabs/databend/runs/4323005954?check_suite_focus=true#step:5:1901

**Comment by BohuTANG** [comment]
main branch test is ok now, not sure it related to the github macos runner issue
