### ISSUE TITLE
Build website failure

### ISSUE THREAD

**Issue by zhang2014** [datafuselabs/databend#3283]
**Summary**

CC: @Xuanwo 

```
:> npm start

Compiled with problems:X

ERROR in ./docs/cli/images/bendctl-how-to-use.gif (./node_modules/url-loader/dist/cjs.js?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!./docs/cli/images/bendctl-how-to-use.gif)

Module build failed: Error: Unknown keyword formatMinimum
    at get (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:25:15)
    at ajvKeywords (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:10:13)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/validate.js:58:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)


ERROR in ./docs/development/images/profiling-flamegraph.png (./node_modules/url-loader/dist/cjs.js?limit=10000&name=assets/images/[name]-[hash].[ext]&fallback=file-loader!./docs/development/images/profiling-flamegraph.png)

Module build failed: Error: Unknown keyword formatMinimum
    at get (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:25:15)
    at ajvKeywords (/Users/winter/Source/databend/website/databend/node_modules/_ajv-keywords@5.1.0@ajv-keywords/dist/index.js:10:13)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/validate.js:58:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/winter/Source/databend/website/databend/node_modules/schema-utils/dist/index.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by Xuanwo** [comment]
I can't reproduce this error and it's not reproducible by vercel's runtime either.

Can you provide more detail about your environment? What's NodeJS version are you using?

**Comment by zhang2014** [comment]
```
MacOS monterey 12.0.1
node --version. v17.2.0
npm --version 7.24.2

 npm run build

> databend@0.0.0 build
> docusaurus build


[en] Creating an optimized production build...

✖ Client
  Compiled with some errors in 9.84s

● Server █████████████████████████ building (64%) 1/1 entries 2234/2234 dependencies 770/770 modules 0 active 
 



Error: Unknown keyword formatMinimum
Module build failed: Error: Unknown keyword formatMinimum
Client bundle compiled with errors therefore further build is impossible.
```

**Comment by Xuanwo** [comment]
It's more like an upstream issue, I have created an issue https://github.com/facebook/docusaurus/issues/6073 to track it, please keep an eye on it.
