### ISSUE TITLE
test: flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#3411]
**Summary**

Test faild on github CI and my local:

https://github.com/datafuselabs/databend/runs/4500949403?check_suite_focus=true
github CI:
```
failures:

---- flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read stdout ----
Error: timeout after 3s when a leader is observed latest: RaftMetrics { id: 0, state: Candidate, current_term: 2, last_log_index: 11, last_applied: 11, current_leader: None, membership_config: MembershipConfig { members: {0, 1, 2}, members_after_consensus: None }, snapshot: LogId { term: 0, index: 0 }, leader_metrics: None }

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/error.rs:530:25
   1: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/result.rs:1911:27
   2: it::flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read::{{closure}}
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:502:13
  12:     0x564ef9881084 - std::sys_common::backtrace::__rust_end_short_backtrace::hb2740127084ae930
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x564ef9883fc9 - rust_begin_unwind
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:498:5
  14:     0x564ef0db11c1 - core::panicking::panic_fmt::h7b8580d81fcbbacd
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panicking.rs:107:14
  15:     0x564ef98d971e - core::panicking::assert_failed_inner::hc71171cfb6f4bc69
  16:     0x564ef835631c - core::panicking::assert_failed::ha7a97b8a8fe50941
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panicking.rs:145:5
  17:     0x564ef10f4835 - test::assert_test_result::hab0d1a9ac07e3d46
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:195:5
  18:     0x564ef13ea05f - it::flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read::{{closure}}::h0d77d679a3fe79de
                               at /home/runner/work/databend/databend/metasrv/tests/it/flight/metasrv_flight_meta_api_restart_cluster.rs:34:7
  19:     0x564ef103be7e - core::ops::function::FnOnce::call_once::hdb3d02641c429b58
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
  20:     0x564ef15d7ee3 - core::ops::function::FnOnce::call_once::h72f0ed8108161f8a
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
  21:     0x564ef15d7ee3 - test::__rust_begin_short_backtrace::h16913019d6add626
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:585:5
  22:     0x564ef15d6af7 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h14ee097d0989e249
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/alloc/src/boxed.rs:1694:9
  23:     0x564ef15d6af7 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h34da45e9ffe1650b
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panic/unwind_safe.rs:271:9
  24:     0x564ef15d6af7 - std::panicking::try::do_call::hc2f59cf7e8b34d98
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:406:40
  25:     0x564ef15d6af7 - std::panicking::try::h9ad5dc489a0b95ea
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:370:19
  26:     0x564ef15d6af7 - std::panic::catch_unwind::h2942dca60008e3ac
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panic.rs:133:14
  27:     0x564ef15d6af7 - test::run_test_in_process::hb3d0263ecf4838c0
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:608:18
  28:     0x564ef15d6af7 - test::run_test::run_test_inner::{{closure}}::h4dc85184b30bfcfa
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:500:39
  29:     0x564ef15a13de - test::run_test::run_test_inner::{{closure}}::ha3a4b379272dea29
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:527:37
  30:     0x564ef15a13de - std::sys_common::backtrace::__rust_begin_short_backtrace::h442b5404c7b13203
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:123:18
  31:     0x564ef15a7218 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::ha544bffd50245a0a
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/thread/mod.rs:484:17
  32:     0x564ef15a7218 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h266b55028ccbc85b
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panic/unwind_safe.rs:271:9
  33:     0x564ef15a7218 - std::panicking::try::do_call::h9867f7a39e4a9b88
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:406:40
  34:     0x564ef15a7218 - std::panicking::try::h44280820c68c27a9
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:370:19
  35:     0x564ef15a7218 - std::panic::catch_unwind::h119a231bd2672a37
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panic.rs:133:14
  36:     0x564ef15a7218 - std::thread::Builder::spawn_unchecked::{{closure}}::h8d52eb920005dafe
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/thread/mod.rs:483:30
  37:     0x564ef15a7218 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hdf93cb2f76bab397
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
  38:     0x564ef988f6b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7e635c32f26a8aad
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/alloc/src/boxed.rs:1694:9
  39:     0x564ef988f6b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h831eb4ef439f373d
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/alloc/src/boxed.rs:1694:9
  40:     0x564ef988f6b3 - std::sys::unix::thread::Thread::new::thread_start::hf8ddbd80a62037f9
                               at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f886f1d8609 - start_thread
  42:     0x7f886ec19293 - clone
  43:                0x0 - <unknown>


failures:
    flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read

```

Local:
```
failures:

---- flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read stdout ----
Error: timeout after 3s when a leader is observed latest: RaftMetrics { id: 0, state: Candidate, current_term: 2, last_log_index: 11, last_applied: 11, current_leader: None, membership_config: MembershipConfig { members: {0, 1, 2}, members_after_consensus: None }, snapshot: LogId { term: 0, index: 0 }, leader_metrics: None }
thread 'flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:195:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    flight::metasrv_flight_meta_api_restart_cluster::test_meta_api_restart_cluster_write_read

test result: FAILED. 56 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 19.25s

```

**Comment by drmingdrmer** [comment]
Timeout is too short.
Let me extend it!
