### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by GrapeBaBa** [datafuselabs/databend#3551]
Make sure that `git diff` result is empty and you've just pulled fresh main, and run first:
```text
$ make setup
```
Yes.

**Operating system**

OS kind or distribution, specific version/release, non-standard kernel if any. If you are trying to build inside virtual machine, please mention it too.

**rust version**
```text
$ rustc --version
$ cargo --version
```
rustc 1.59.0-nightly (6db0a0e9a 2021-11-29)
cargo 1.58.0-nightly (7f08ace4f 2021-11-24)

**Databend git version**
commit 299c31a980d86ae4ad3ac16dd7623c9d412cf864

```
failures:

---- flight::metasrv_flight_kv_api_restart_cluster::test_kv_api_restart_cluster_write_read stdout ----
Error: Code: 4007, displayText = Raft is shutting down.
thread 'flight::metasrv_flight_kv_api_restart_cluster::test_kv_api_restart_cluster_write_read' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:195:5

---- flight::metasrv_flight_meta_api_follower_follower::test_meta_api_list_table stdout ----
thread 'flight::metasrv_flight_meta_api_follower_follower::test_meta_api_list_table' panicked at 'assertion failed: res.is_ok()', /Users/kaichen/Documents/projects/databend/common/meta/api/src/meta_api_test_suite.rs:590:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- meta_node::meta_node_all::test_meta_node_snapshot_replication stdout ----
Error: timeout after 10s when non-voter replicated all logs .last_log_index -> 15 latest: RaftMetrics { id: 1, state: NonVoter, current_term: 1, last_log_index: 0, last_applied: 0, current_leader: Some(0), membership_config: MembershipConfig { members: {1}, members_after_consensus: None }, snapshot: LogId { term: 0, index: 0 }, leader_metrics: None }
thread 'meta_node::meta_node_all::test_meta_node_snapshot_replication' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:195:5


failures:
    flight::metasrv_flight_kv_api_restart_cluster::test_kv_api_restart_cluster_write_read
    flight::metasrv_flight_meta_api_follower_follower::test_meta_api_list_table
    meta_node::meta_node_all::test_meta_node_snapshot_replication

test result: FAILED. 54 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 31.70s
```

**Comment by drmingdrmer** [comment]
Thank you for reporting this issue.

Does it always fail or has chance to pass?

BTW can you please run it with `RUST_BACKTRACE=1 RUST_LOG=debug cargo test` and attach the stdout and the debug log in `metasrv/_logs`? 
These info would help a lot on debugging this issue.

**Comment by GrapeBaBa** [comment]
`meta_node::meta_node_all::test_meta_node_snapshot_replication` this one frequently occur.

**Comment by GrapeBaBa** [comment]
> Thank you for reporting this issue.
> 
> Does it always fail or has chance to pass?
> 
> BTW can you please run it with `RUST_BACKTRACE=1 RUST_LOG=debug cargo test` and attach the stdout and the debug log in `metasrv/_logs`? These info would help a lot on debugging this issue.

@drmingdrmer the backtrace

```
Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/backtrace.rs:328:13
   3: std::backtrace::Backtrace::capture
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/backtrace.rs:296:9
   4: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/anyhow-1.0.51/src/error.rs:530:25
   5: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/result.rs:1911:27
   6: it::meta_node::meta_node_all::test_meta_node_snapshot_replication::{{closure}}
             at ./tests/it/meta_node/meta_node_all.rs:348:5
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/future/mod.rs:80:19
   8: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/park/thread.rs:263:54
   9: tokio::coop::with_budget::{{closure}}
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:102:9
  10: std::thread::local::LocalKey<T>::try_with
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/thread/local.rs:399:16
  11: std::thread::local::LocalKey<T>::with
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/thread/local.rs:375:9
  12: tokio::coop::with_budget
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:95:5
  13: tokio::coop::budget
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/coop.rs:72:5
  14: tokio::park::thread::CachedParkThread::block_on
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/park/thread.rs:263:31
  15: tokio::runtime::enter::Enter::block_on
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/enter.rs:151:13
  16: tokio::runtime::thread_pool::ThreadPool::block_on
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/thread_pool/mod.rs:77:9
  17: tokio::runtime::Runtime::block_on
             at /Users/kaichen/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.15.0/src/runtime/mod.rs:463:43
  18: it::meta_node::meta_node_all::test_meta_node_snapshot_replication
             at ./tests/it/meta_node/meta_node_all.rs:374:5
  19: it::meta_node::meta_node_all::test_meta_node_snapshot_replication::{{closure}}
             at ./tests/it/meta_node/meta_node_all.rs:275:7
  20: core::ops::function::FnOnce::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
  22: test::__rust_begin_short_backtrace
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:585:5
  23: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/alloc/src/boxed.rs:1694:9
  24: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panic/unwind_safe.rs:271:9
  25: std::panicking::try::do_call
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:406:40
  26: std::panicking::try
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:370:19
  27: std::panic::catch_unwind
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panic.rs:133:14
  28: test::run_test_in_process
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:608:18
  29: test::run_test::run_test_inner::{{closure}}
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:500:39
  30: test::run_test::run_test_inner::{{closure}}
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:527:37
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys_common/backtrace.rs:123:18
  32: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/thread/mod.rs:484:17
  33: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panic/unwind_safe.rs:271:9
  34: std::panicking::try::do_call
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:406:40
  35: std::panicking::try
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:370:19
  36: std::panic::catch_unwind
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panic.rs:133:14
  37: std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/thread/mod.rs:483:30
  38: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
  39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/alloc/src/boxed.rs:1694:9
  40: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/alloc/src/boxed.rs:1694:9
  41: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/sys/unix/thread.rs:108:17
  42: __pthread_start
thread 'meta_node::meta_node_all::test_meta_node_snapshot_replication' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: the test returned a termination value with a non-zero status code (1) which indicates a failure', /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:195:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panicking.rs:107:14
   2: core::panicking::assert_failed_inner
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panicking.rs:182:23
   3: core::panicking::assert_failed
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/panicking.rs:145:5
   4: test::assert_test_result
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/test/src/lib.rs:195:5
   5: it::meta_node::meta_node_all::test_meta_node_snapshot_replication::{{closure}}
             at ./tests/it/meta_node/meta_node_all.rs:275:7
   6: core::ops::function::FnOnce::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by drmingdrmer** [comment]
It is because somehow the task is blocked by other unit test threads and finally timed out.

The log shows that `test_meta_node_snapshot_replication` is delayed by about 3 seconds.

```
2021-12-21T02:27:21.534917Z DEBUG ThreadId(221) ut{test_meta_node_snapshot_replication}:open_create_boot{open=None create=Some(()) init_cluster=None ...

...

2021-12-21T02:27:24.655324Z DEBUG ThreadId(216) ut{test_meta_node_snapshot_replication}:log...

```

`RUST_TEST_THREADS=1 cargo test` should let the unit tests pass happily.

We've had several issues like yours in the past. For the same reason, in our CI unit test threads are limited to 2. Otherwise the CI fails a lot because of limited resource.
