### ISSUE TITLE
ci: Workflow skipped for runner no space left

### ISSUE THREAD

**Issue by ariesdevil** [datafuselabs/databend#3562]
**Summary**
Hi, I encounter the ubuntu unit test skipped today and after rerunning it all, it still happened.

related PR: #3532 

cc @Xuanwo

**Comment by Xuanwo** [comment]
Let me take a look.

**Comment by Xuanwo** [comment]
```shell
test_unit (ubuntu-latest, x86_64-unknown-linux-gnu)
Unhandled exception. System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at System.Diagnostics.TraceSource.Flush()
   at GitHub.Runner.Common.TraceManager.Dispose(Boolean disposing)
   at GitHub.Runner.Common.TraceManager.Dispose()
   at GitHub.Runner.Common.HostContext.Dispose(Boolean disposing)
   at GitHub.Runner.Common.HostContext.Dispose()
   at GitHub.Runner.Worker.Program.Main(String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Worker.Worker.RunAsync(String pipeIn, String pipeOut)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
System.IO.IOException: No space left on device
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.Diagnostics.TextWriterTraceListener.Flush()
   at GitHub.Runner.Common.HostTraceListener.WriteHeader(String source, TraceEventType eventType, Int32 id)
   at GitHub.Runner.Common.HostTraceListener.TraceEvent(TraceEventCache eventCache, String source, TraceEventType eventType, Int32 id, String message)
   at System.Diagnostics.TraceSource.TraceEvent(TraceEventType eventType, Int32 id, String message)
   at GitHub.Runner.Common.Tracing.Error(Exception exception)
   at GitHub.Runner.Worker.Program.MainAsync(IHostContext context, String[] args)
```

From: https://github.com/datafuselabs/databend/actions/runs/1600648091

---

Github has a limit of 20GB on disk, will we produce too many files in the unit tests? If not, Github must be sucks.

**Comment by ariesdevil** [comment]
Does the macOS unit test have different behavior with ubuntu or Github disk limit is not the same?
cc @PsiACE

**Comment by Xuanwo** [comment]
It looks they are the same:

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

![image](https://user-images.githubusercontent.com/5351546/146734746-f2d4efa5-5432-4865-9949-5b820b04f15a.png)

---

BTW, I did a clean `cargo test --all-features --no-fail-fast` on my Linux host:

```shell
:) du -h .
18G     .
```

**Comment by ariesdevil** [comment]
Wow...so big

**Comment by Xuanwo** [comment]
Here is a workaround from the community: https://github.community/t/error-no-space-left-on-device/156746/4

We can use https://github.com/apache/flink/blob/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh to remove no used files

**Comment by Xuanwo** [comment]
ping @ariesdevil, Please try merge #3565 to verify whether it works or not.

**Comment by ariesdevil** [comment]
> ping @ariesdevil, Please try merge #3565 to verify whether it works or not.

Got
