### ISSUE TITLE
Flaky test servers::http::http_query_handlers::test_async

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4080]
**Summary**

```
failures:

---- servers::http::http_query_handlers::test_async stdout ----
thread 'servers::http::http_query_handlers::test_async' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<0
>1

', query/tests/it/servers/http/http_query_handlers.rs:119:9
stack backtrace:
   0:     0x55ebd51626bc - std::backtrace_rs::backtrace::libunwind::trace::h508eb199ca9e489d
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55ebd51626bc - std::backtrace_rs::backtrace::trace_unsynchronized::h161df61e809db333
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55ebd51626bc - std::sys_common::backtrace::_print_fmt::h2770cfc3b1d87576
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55ebd51626bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h563ba30d61935f58
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55ebd51c2b0c - core::fmt::write::h38da4b8ad8c9b0ca
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/core/src/fmt/mod.rs:1190:17
   5:     0x55ebd5151cb3 - std::io::Write::write_fmt::haf39a6325ce0294c
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/io/mod.rs:1653:15
   6:     0x55ebd51669a1 - std::sys_common::backtrace::_print::hf0c3fdfcf4fe3a40
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55ebd51669a1 - std::sys_common::backtrace::print::h7fb9681b360d5f0f
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55ebd51669a1 - std::panicking::default_hook::{{closure}}::hced02a38ced47401
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panicking.rs:295:22
   9:     0x55ebd51666cb - std::panicking::default_hook::h03f76e2c951cd926
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panicking.rs:311:9
  10:     0x55ebd5167264 - std::panicking::rust_panic_with_hook::hf69c531f680b680b
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panicking.rs:698:17
  11:     0x55ebd5166f47 - std::panicking::begin_panic_handler::{{closure}}::h3509bb68e184c6c5
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panicking.rs:588:13
  12:     0x55ebd5162b64 - std::sys_common::backtrace::__rust_end_short_backtrace::h9de973f77cb459c7
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55ebd5166c49 - rust_begin_unwind
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panicking.rs:584:5
  14:     0x55ebc3fc47c3 - core::panicking::panic_fmt::h8d2d16457c4ed0e2
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/core/src/panicking.rs:135:14
  15:     0x55ebc440187a - it::servers::http::http_query_handlers::test_async::{{closure}}::hd1eb7e2241c461a4
                               at /home/runner/work/databend/databend/query/tests/it/servers/http/http_query_handlers.rs:119:9
  16:     0x55ebc479b599 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h833bbe5829fae3b9
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/core/src/future/mod.rs:84:19
  17:     0x55ebc477fc00 - <core::pin::Pin<P> as core::future::future::Future>::poll::h4d444984061970d8
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/core/src/future/future.rs:123:9
  18:     0x55ebc46fbdd2 - tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}::h45873e0a65ccf44c
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/test/src/lib.rs:598:18
  44:     0x55ebc4946d89 - test::run_test::run_test_inner::{{closure}}::hd4b78ab2d90bb430
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/test/src/lib.rs:492:39
  45:     0x55ebc4951f71 - test::run_test::run_test_inner::{{closure}}::hc5ef8ecc617d9d09
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/test/src/lib.rs:519:37
  46:     0x55ebc4951f71 - std::sys_common::backtrace::__rust_begin_short_backtrace::h6c705132e9c389b0
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/sys_common/backtrace.rs:122:18
  47:     0x55ebc491a09f - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hdec3e20896f52bff
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/thread/mod.rs:498:17
  48:     0x55ebc491a09f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h33deef33de17f001
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/core/src/panic/unwind_safe.rs:271:9
  49:     0x55ebc491a09f - std::panicking::try::do_call::h58e46747ca22a19e
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panicking.rs:492:40
  50:     0x55ebc491a09f - std::panicking::try::heb3719a0b3929151
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panicking.rs:456:19
  51:     0x55ebc491a09f - std::panic::catch_unwind::h8f3d2517db12ef3d
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/panic.rs:137:14
  52:     0x55ebc491a09f - std::thread::Builder::spawn_unchecked_::{{closure}}::h661f0e22576b8c79
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/thread/mod.rs:497:30
  53:     0x55ebc491a09f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4085074f99ab9783
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/core/src/ops/function.rs:227:5
  54:     0x55ebd5173193 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h5040ebd4d05cfbe0
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/alloc/src/boxed.rs:1854:9
  55:     0x55ebd5173193 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h9f2a7aba330dbbd9
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/alloc/src/boxed.rs:1854:9
  56:     0x55ebd5173193 - std::sys::unix::thread::Thread::new::thread_start::hdb72b219a1fa43cf
                               at /rustc/f624427f8771c00819684c783bb841bf72095704/library/std/src/sys/unix/thread.rs:108:17
  57:     0x7f536f0da609 - start_thread
  58:     0x7f536eb1b293 - clone
  59:                0x0 - <unknown>


failures:
    servers::http::http_query_handlers::test_async

test result: FAILED. 219 passed; 1 failed; 1 ignored; 0 measured; 0 filtered out; finished in 21.57s

   Doc-tests dal_context

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

error: test failed, to rerun pass '-p databend-query --test it'

```

https://github.com/datafuselabs/databend/runs/5120558495?check_suite_focus=true#step:3:1255

**Comment by BohuTANG** [comment]
I'll disable this test temporarily in #4082

**Comment by youngsofun** [comment]
sorry for not noticing your message earlier
it is my fault, I reduced the sleep/wait time to avoid taking too much test running time, I tested it multi-times on my mac.
I will try to find a better way to make this test stable

**Comment by BohuTANG** [comment]
Hello, How about this flaky test going?
Also welcome someone to take this issue, labeled with `good first issue`.
