### ISSUE TITLE
Flaky test:servers::http::http_query_handlers::test_multi_page

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#4327]
A flaky test:
```
failures:

---- servers::http::http_query_handlers::test_multi_page stdout ----
thread 'servers::http::http_query_handlers::test_multi_page' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<0
>10000

', query/tests/it/servers/http/http_query_handlers.rs:202:5
stack backtrace:
   0:     0x55b75acb911c - std::backtrace_rs::backtrace::libunwind::trace::h3378927f541f6c04
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55b75acb911c - std::backtrace_rs::backtrace::trace_unsynchronized::hdb4c2fa83db93444
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b75acb911c - std::sys_common::backtrace::_print_fmt::hcd86ae48a4354c57
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55b75acb911c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h39278ceede34f184
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55b75ace4dec - core::fmt::write::hdc75737b203416ad
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/fmt/mod.rs:[1190](https://github.com/datafuselabs/databend/runs/5419435135?check_suite_focus=true#step:3:1190):17
   5:     0x55b75acaf648 - std::io::Write::write_fmt::h8f7aced95ccfd0dc
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/ops/function.rs:227:5
  31:     0x55b7528e07b3 - test::__rust_begin_short_backtrace::hb863b53415a6c3c8
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/test/src/lib.rs:575:5
  32:     0x55b7528df43f - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h6e7d1f9d5fd8a255
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
  33:     0x55b7528df43f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he22973c0157abcad
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
  34:     0x55b7528df43f - std::panicking::try::do_call::hc40de4a913926a63
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
  35:     0x55b7528df43f - std::panicking::try::h2ce93d83ee76f146
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
  36:     0x55b7528df43f - std::panic::catch_unwind::hea9bd4ca39274840
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
  37:     0x55b7528df43f - test::run_test_in_process::h66e031868634c23a
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/test/src/lib.rs:598:18
  38:     0x55b7528df43f - test::run_test::run_test_inner::{{closure}}::h374c2d96e09a6fdc
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/test/src/lib.rs:492:39
  39:     0x55b7528e9201 - test::run_test::run_test_inner::{{closure}}::h04c08617f7ade054
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/test/src/lib.rs:519:37
  40:     0x55b7528e9201 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9ba773678c27c051
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys_common/backtrace.rs:122:18
  41:     0x55b7528b529f - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::hbe6a7761dbab7a63
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:498:17
  42:     0x55b7528b529f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h27450c879e029fc9
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/panic/unwind_safe.rs:271:9
  43:     0x55b7528b529f - std::panicking::try::do_call::h61592e92ca7f0dc1
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:492:40
  44:     0x55b7528b529f - std::panicking::try::h200a14ed0a35be11
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panicking.rs:456:19
  45:     0x55b7528b529f - std::panic::catch_unwind::hbfa0137f754138a7
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/panic.rs:137:14
  46:     0x55b7528b529f - std::thread::Builder::spawn_unchecked_::{{closure}}::h5bb3256bb0dd33f1
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/thread/mod.rs:497:30
  47:     0x55b7528b529f - core::ops::function::FnOnce::call_once{{vtable.shim}}::hfa0492591cec1bda
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/core/src/ops/function.rs:227:5
  48:     0x55b75acc3653 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h8ab0aa77c9fe664a
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
  49:     0x55b75acc3653 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hd82178596e9e381e
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/alloc/src/boxed.rs:1854:9
  50:     0x55b75acc3653 - std::sys::unix::thread::Thread::new::thread_start::hf4d984fb21d4c83d
                               at /rustc/4ce3749235fc31d15ebd444b038a9877e8c700d7/library/std/src/sys/unix/thread.rs:108:17
  51:     0x7fd97fba8609 - start_thread
  52:     0x7fd97f5e9293 - clone
  53:                0x0 - <unknown>


failures:
    servers::http::http_query_handlers::test_multi_page
```

_Originally posted by @BohuTANG in https://github.com/datafuselabs/databend/issues/4325#issuecomment-1059014010_

**Comment by BohuTANG** [comment]
Caused by https://github.com/datafuselabs/databend/pull/4325
