### ISSUE TITLE
flaky 02_0000_kill_query

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#5472]
**Summary**

flaky test:
```
02_0000_kill_query:                                                     2022-05-19T11:58:23.079983Z ERROR databend_query::pipelines::processors::processor_merge: Merge processor cannot push data: channel closed
[ FAIL ] - return code 1
, result:

Traceback (most recent call last):
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 178, in read
    data += self.queue.get(timeout=timeleft)
  File "/usr/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 152, in expect
    data = self.read(timeout=timeleft, raise_exception=True)
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 186, in read
    raise TimeoutError(timeout)
uexpect.TimeoutError: Timeout 60.000s

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/02_0000_kill_query.py", line 25, in <module>
    with NativeClient(name='client2>') as client2:
  File "/home/runner/work/databend/databend/tests/suites/1_stateful/02_query/../../../helpers/native_client.py", line 38, in __init__
    self.client.expect('[#\$] ', timeout=60)
  File "/home/runner/work/databend/databend/tests/helpers/uexpect.py", line 159, in expect
    raise exception
uexpect.ExpectTimeoutError: Timeout 60.000s for '[#\\$] ' 
```

https://github.com/datafuselabs/databend/runs/6506657787?check_suite_focus=true#step:3:210

**Comment by BohuTANG** [comment]
I think we need to cancel the task in the new processor, now we can't do it? cc @zhang2014

**Comment by zhang2014** [comment]
The error does not appear to be running in the new processor. 

```
databend_query::pipelines::processors::processor_merge
```

**Comment by TCeason** [comment]
Yes in this test set new processor = 0;

This is use new processor's error:

```

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

root@mysqldb 11:54:52 [(none)]> select * from numbers(99999999999999);
^C^C -- query aborted
ERROR 1152 (08S01): Code: 1043, displayText = Aborted query, because the server is shutting down or the query was killed.
root@mysqldb 11:55:00 [(none)]> select * from numbers(99999999999999);
ERROR 1105 (HY000): Code: 1015, displayText = Cannot found edge in graph, edge_index: EdgeIndex(32523), graph: digraph {
    0 [ label = "0" ]
    1 [ label = "1" ]
    2 [ label = "2" ]
    3 [ label = "3" ]
    4 [ label = "4" ]
    5 [ label = "5" ]
    6 [ label = "6" ]
    7 [ label = "7" ]
    8 [ label = "8" ]
    9 [ label = "9" ]
    10 [ label = "10" ]
    11 [ label = "11" ]
    12 [ label = "12" ]
    13 [ label = "13" ]
    14 [ label = "14" ]
    15 [ label = "15" ]
    16 [ label = "16" ]
    17 [ label = "17" 

```

**Comment by TCeason** [comment]
> Maybe this not run in new processor?
> 
> ```
> databend_query::pipelines::processors::processor_merge
> ```

Yes in this test set new processor = 0;

This is use new processor's error:

```

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

root@mysqldb 11:54:52 [(none)]> select * from numbers(99999999999999);
^C^C -- query aborted
ERROR 1152 (08S01): Code: 1043, displayText = Aborted query, because the server is shutting down or the query was killed.
root@mysqldb 11:55:00 [(none)]> select * from numbers(99999999999999);
ERROR 1105 (HY000): Code: 1015, displayText = Cannot found edge in graph, edge_index: EdgeIndex(32523), graph: digraph {
    0 [ label = "0" ]
    1 [ label = "1" ]
    2 [ label = "2" ]
    3 [ label = "3" ]
    4 [ label = "4" ]
    5 [ label = "5" ]
    6 [ label = "6" ]
    7 [ label = "7" ]
    8 [ label = "8" ]
    9 [ label = "9" ]
    10 [ label = "10" ]
    11 [ label = "11" ]
    12 [ label = "12" ]
    13 [ label = "13" ]
    14 [ label = "14" ]
    15 [ label = "15" ]
    16 [ label = "16" ]
    17 [ label = "17" 

```
