### ISSUE TITLE
bug:  jdbc query databend failed

### ISSUE THREAD

**Issue by sandflee** [datafuselabs/databend#6147]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

610f381404313f6944fd89b5460ae5eb0bfd6717

### What's Wrong?

jdbc logs:
```
java.sql.SQLException: Code: 2801, displayText = Unknown variable: "SQL_SELECT_LIMIT".
  at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:964) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.ConnectionImpl.setSessionMaxRows(ConnectionImpl.java:5432) ~[mysql-connector-java-5.1.40.jar:5.1.40]
  at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1365) ~[mysql-connector-java-5.1.40.jar:5.1.40]
```

databend logs:
```
2022-06-22T10:44:37.225292Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Federated query: SET NAMES utf8
2022-06-22T10:44:37.257333Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Federated query: SET character_set_results = NULL
2022-06-22T10:44:37.289192Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Federated query: SET sql_mode='0,STRICT_TRANS_TABLES'
2022-06-22T10:44:37.353577Z  INFO databend_query::servers::mysql::mysql_interactive_worker: Normal query: SET SQL_SELECT_LIMIT=1000

```

### How to Reproduce?

1. start databend cluster
3. run sql using java jdbc,   mysql connector version is "mysql-connector-java-5.1.40 ( Revision: 402933ef52cad9aa82624e80acbea46e3a701ce6 )"

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by BohuTANG** [comment]
cc @TCeason
