### ISSUE TITLE
bug:  copy into from remote  failed 

### ISSUE THREAD

**Issue by wubx** [datafuselabs/databend#7985]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

```
+-----------------------------------------------------------------------------------------+
| version()                                                                               |
+-----------------------------------------------------------------------------------------+
| 8.0.26-v0.8.54-nightly-bcdf260-simd(rust-1.66.0-nightly-2022-09-29T16:23:33.037160103Z) |
+-----------------------------------------------------------------------------------------+
1 row in set (0.03 sec)
```

### What's Wrong?

```
Traceback (most recent call last):
  File "tc.py", line 43, in <module>
    r = engine.execute(sql)
  File "<string>", line 2, in execute
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3008, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1185, in execute
    return self._exec_driver_sql(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1484, in _exec_driver_sql
    ret = self._execute_context(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1748, in _execute_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1933, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
  File "/home/ubuntu/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_context
    self.dialect.do_execute(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/base.py", line 391, in do_execute
    cursor.execute(statement, parameters, context=context)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/http/connector.py", line 122, in execute
    self._process_response(response_gen)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/http/connector.py", line 221, in _process_response
    self._columns = next(response, None)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/http/transport.py", line 131, in execute
    r = self._send(query, params=params, stream=True)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/clickhouse_sqlalchemy/drivers/http/transport.py", line 177, in _send
    raise DatabaseException(orig)
clickhouse_sqlalchemy.exceptions.DatabaseException: Orig exception: Code: 1104, displayText = assertion failed: `(left == right)`
  left: `Reading`,
 right: `Done`.
```

### How to Reproduce?

table schema:
```
CREATE TABLE `github_base` (
  `id` VARCHAR,
  `type` VARCHAR,
  `actor` VARIANT,
  `repo` VARIANT,
  `payload` VARIANT,
  `public` BOOLEAN,
  `created_at` TIMESTAMP(0),
  `org` VARIANT
) ENGINE=FUSE
```

pip install SQLAlchemy==1.4
pip install clickhouse-sqlalchemy==0.2.1

```
from distutils.util import execute
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import calendar

def get_mday(year, month):
    monthRange = calendar.monthrange(year,month)
    return(monthRange[1])

mday = get_mday(2022,1)
#print(mday)

def gen_tbname(year,month, mday):
    t_list =[]
    copy_list = []
    for t in range(1,mday+1):
        tb_name="github_%d%02d%02d"%(year,month,t)
        t_list.append(tb_name)
        url="COPY INTO  %s FROM 'https://data.gharchive.org/%d-%02d-%02d-[0-23].json.gz' FILE_FORMAT = ( TYPE =NDJSON compression = auto ) force=true"%(tb_name, year, month, t)
        copy_list.append(url)
    return(t_list, copy_list)


tb_l = gen_tbname(2022,1,31)

conn_str = 'clickhouse+http://root:@127.0.0.1:8124/github_v2?protocol=http'
engine = create_engine(conn_str, connect_args={'protocol': 'http', 'port': 8124})


for tb in tb_l[0]:
    engine.execute("drop table if exists %s all"%(tb))
    sql="create table if not exists %s like github.github_base"%(tb)
    print(sql)
    engine.execute(sql)



r = engine.execute("show tables")
print(r.fetchall())

for sql in tb_l[1]:
    print(sql)
    r = engine.execute(sql)
    print(r.fetchall())
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by wubx** [comment]
query log 
```
{
	"v": 0,
	"name": "databend-query-test_tenant-test_cluster",
	"msg": "copy split reader error: Code: 4000, displayText = operation interrupted (request or response body error: error reading a body from connection: end of file before message length reached).\n\n<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> ",
	"level": 50,
	"hostname": "VM-0-17-ubuntu",
	"pid": 993898,
	"time": "2022-09-29T01:40:35.35061295Z",
	"target": "common_pipeline_sources::processors::sources::input_formats::input_pipeline",
	"line": 151,
	"file": "src/query/pipeline/sources/src/processors/sources/input_formats/input_pipeline.rs"
} {
	"v": 0,
	"name": "databend-query-test_tenant-test_cluster",
	"msg": "panicked at 'assertion failed: `(left == right)`\n  left: `Reading`,\n right: `Done`', src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs:327:17",
	"level": 50,
	"hostname": "VM-0-17-ubuntu",
	"pid": 993898,
	"time": "2022-09-29T01:40:36.441063396Z",
	"target": "common_tracing::panic_hook",
	"line": 36,
	"file": "src/common/tracing/src/panic_hook.rs",
	"panic.column": 17,
	"backtrace": "Backtrace [{ fn: \"common_tracing::panic_hook::log_panic\", file: \"/workspace/src/common/tracing/src/panic_hook.rs\", line: 33 }, { fn: \"std::panicking::rust_panic_with_hook\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 702 }, { fn: \"std::panicking::begin_panic_handler::{{closure}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 588 }, { fn: \"std::sys_common::backtrace::__rust_end_short_backtrace\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs\", line: 138 }, { fn: \"rust_begin_unwind\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 584 }, { fn: \"core::panicking::panic_fmt\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panicking.rs\", line: 142 }, { fn: \"core::panicking::assert_failed_inner\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panicking.rs\" }, { fn: \"core::panicking::assert_failed\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panicking.rs\", line: 181 }, { fn: \"<common_pipeline_sources::processors::sources::input_formats::input_format_text::AligningState<T> as common_pipeline_sources::processors::sources::input_formats::input_pipeline::AligningStateTrait>::align\", file: \"/workspace/src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs\", line: 327 }, { fn: \"<common_pipeline_sources::processors::sources::input_formats::source_aligner::Aligner<I> as common_pipeline_core::processors::processor::Processor>::process\", file: \"/workspace/src/query/pipeline/sources/src/processors/sources/input_formats/source_aligner.rs\", line: 119 }, { fn: \"common_pipeline_core::processors::processor::ProcessorPtr::process\", file: \"/workspace/src/query/pipeline/core/src/processors/processor.rs\", line: 101 }, { fn: \"databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_sync_task\", file: \"/workspace/src/query/service/src/pipelines/executor/executor_worker_context.rs\", line: 82 }, { fn: \"databend_query::pipelines::executor::executor_worker_context::ExecutorWorkerContext::execute_task\", file: \"/workspace/src/query/service/src/pipelines/executor/executor_worker_context.rs\", line: 72 }, { fn: \"databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_single_thread\", file: \"/workspace/src/query/service/src/pipelines/executor/pipeline_executor.rs\", line: 247 }, { fn: \"databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}::{{closure}}\", file: \"/workspace/src/query/service/src/pipelines/executor/pipeline_executor.rs\", line: 213 }, { fn: \"<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs\", line: 271 }, { fn: \"std::panicking::try::do_call\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 492 }, { fn: \"std::panicking::try\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 456 }, { fn: \"std::panic::catch_unwind\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs\", line: 137 }, { fn: \"common_base::base::catch_unwind::catch_unwind\", file: \"/workspace/src/common/base/src/base/catch_unwind.rs\", line: 19 }, { fn: \"databend_query::pipelines::executor::pipeline_executor::PipelineExecutor::execute_threads::{{closure}}\", file: \"/workspace/src/query/service/src/pipelines/executor/pipeline_executor.rs\", line: 212 }, { fn: \"common_base::base::thread::Thread::named_spawn::{{closure}}\", file: \"/workspace/src/common/base/src/base/thread.rs\", line: 76 }, { fn: \"std::sys_common::backtrace::__rust_begin_short_backtrace\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs\", line: 122 }, { fn: \"std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/mod.rs\", line: 514 }, { fn: \"<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs\", line: 271 }, { fn: \"std::panicking::try::do_call\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 492 }, { fn: \"std::panicking::try\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 456 }, { fn: \"std::panic::catch_unwind\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs\", line: 137 }, { fn: \"std::thread::Builder::spawn_unchecked_::{{closure}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/mod.rs\", line: 513 }, { fn: \"core::ops::function::FnOnce::call_once{{vtable.shim}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs\", line: 248 }, { fn: \"<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/alloc/src/boxed.rs\", line: 1940 }, { fn: \"<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/alloc/src/boxed.rs\", line: 1940 }, { fn: \"std::sys::unix::thread::Thread::new::thread_start\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys/unix/thread.rs\", line: 108 }, { fn: \"start_thread\" }, { fn: \"clone\" }]",
	"panic.line": 327,
	"panic.file": "src/query/pipeline/sources/src/processors/sources/input_formats/input_format_text.rs"
}
```

**Comment by Xuanwo** [comment]
Has been fixed.
