### ISSUE TITLE
test: grpc::metasrv_grpc_kv_api::test_metasrv_kv_api' failure

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#8139]
**Summary**

https://github.com/datafuselabs/databend/actions/runs/3227731825/jobs/5282906436#step:4:2407
```
failures:

---- grpc::metasrv_grpc_kv_api::test_metasrv_kv_api stdout ----
thread 'grpc::metasrv_grpc_kv_api::test_metasrv_kv_api' panicked at 'assertion failed: `(left == right)`
  left: `[None, None]`,
 right: `[None, Some(SeqV { seq: 3, meta: Some(KVMeta { expire_at: Some(1665499303) }), data: "[binary]" })]`', /workspace/src/meta/api/src/kv_api_test_suite.rs:289:13
stack backtrace:
   0:     0x5602936b3fc0 - std::backtrace_rs::backtrace::libunwind::trace::h4c56f7c1d2b54c49
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x5602936b3fc0 - std::backtrace_rs::backtrace::trace_unsynchronized::h43647f7dfa7709b7
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5602936b3fc0 - std::sys_common::backtrace::_print_fmt::hb05bf7e901883977
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5602936b3fc0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd3f800102e692f91
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x5602936dde3e - core::fmt::write::h7e5f4e1d134bd366
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/fmt/mod.rs:1202:17
   5:     0x5602936ac195 - std::io::Write::write_fmt::h82862d50e4b3b52e
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/io/mod.rs:1679:15
   6:     0x5602936b5903 - std::sys_common::backtrace::_print::he94aa0f6090079de
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5602936b5903 - std::sys_common::backtrace::print::h925dfd7226e7fc1e
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5602936b5903 - std::panicking::default_hook::{{closure}}::hc105f3dae8d240c7
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:295:22
   9:     0x5602936b5573 - std::panicking::default_hook::h61df943bb9a1db3e
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:311:9
  10:     0x5602936b600a - std::panicking::rust_panic_with_hook::hba475cb83ede0ec8
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:698:17
  11:     0x5602936b5f07 - std::panicking::begin_panic_handler::{{closure}}::h08829afeef0f745a
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:588:13
  12:     0x5602936b446c - std::sys_common::backtrace::__rust_end_short_backtrace::hd1d5fe98bb9a45ac
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5602936b5c22 - rust_begin_unwind
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:584:5
  14:     0x5602936db263 - core::panicking::panic_fmt::hccec6d6a555033fa
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panicking.rs:142:14
  15:     0x5602936db40b - core::panicking::assert_failed_inner::hf076b15a12a5028f
  16:     0x560290d2ee06 - core::panicking::assert_failed::h6be0d9d29b2c943c
  17:     0x5602913ad799 - common_meta_api::kv_api_test_suite::KVApiTestSuite::kv_timeout::{{closure}}::{{closure}}::h6c62f14fdd3991c5
  18:     0x560290c429fe - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hfaeae65ade4a7156
  19:     0x56029139fb5a - common_meta_api::kv_api_test_suite::KVApiTestSuite::kv_timeout::{{closure}}::hcedfdd09898fb61a
  20:     0x560290c3bfde - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hcfb83b85e7687b9c
  21:     0x5602913fabd1 - common_meta_api::kv_api_test_suite::KVApiTestSuite::test_all::{{closure}}::{{closure}}::h86cb004b058c4f90
  22:     0x560290c33afe - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h95a2ac15d98f0985
  23:     0x5602913f64cf - common_meta_api::kv_api_test_suite::KVApiTestSuite::test_all::{{closure}}::hb30fc76b19e852e0
  24:     0x560290c360ee - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha63acc84b6a21bbd
  25:     0x560290f4d63d - it::grpc::metasrv_grpc_kv_api::test_metasrv_kv_api::{{closure}}::h1981038a4cd2b71c
  26:     0x560290c1f19e - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h0daf79626178ac72
  27:     0x560290f3eb22 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::hcfeae929b4b94779
  28:     0x560291105ae6 - tokio::park::thread::CachedParkThread::block_on::{{closure}}::h067ab73d13fb6377
  29:     0x560290d50828 - tokio::coop::with_budget::{{closure}}::hc00e9e68794082ce
  30:     0x560290f6c7b8 - std::thread::local::LocalKey<T>::try_with::h5e502f1f6f9a7960
  31:     0x560290f5e8f8 - std::thread::local::LocalKey<T>::with::he8c7613d64ff2c46
  32:     0x5602910ee2b0 - tokio::park::thread::CachedParkThread::block_on::h725200e9942d4991
  33:     0x560290d5b8b8 - tokio::runtime::enter::Enter::block_on::h5afc1a175d9e0d3e
  34:     0x560290ea9e5b - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hd093557a9dcdaa67
  35:     0x5602914187a8 - tokio::runtime::Runtime::block_on::he882b0d0456ae790
  36:     0x560290f4d3ba - it::grpc::metasrv_grpc_kv_api::test_metasrv_kv_api::he4425e3f54bc2b5d
  37:     0x560290f4c126 - it::grpc::metasrv_grpc_kv_api::test_metasrv_kv_api::{{closure}}::h[2348](https://github.com/datafuselabs/databend/actions/runs/3227731825/jobs/5282906436#step:4:2355)75e5bd7d43b5
  38:     0x560290a6a6ce - core::ops::function::FnOnce::call_once::h651982602ba2b61e
  39:     0x5602914c5d63 - core::ops::function::FnOnce::call_once::hddbe6b3f474ac7aa
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs:248:5
  40:     0x5602914c5d63 - test::__rust_begin_short_backtrace::h35f82049939d5450
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/test/src/lib.rs:572:5
  41:     0x5602914c4a40 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h0cd6a8b4719f4822
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/alloc/src/boxed.rs:1940:9
  42:     0x5602914c4a40 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h8a235d240ab40526
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs:271:9
  43:     0x5602914c4a40 - std::panicking::try::do_call::h9c7bbd241469a084
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:492:40
  44:     0x5602914c4a40 - std::panicking::try::h2acc957c321625d5
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:456:19
  45:     0x5602914c4a40 - std::panic::catch_unwind::h104707e3d18a8caa
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs:137:14
  46:     0x5602914c4a40 - test::run_test_in_process::hdbba4cfa6bbda8b6
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/test/src/lib.rs:595:18
  47:     0x5602914c4a40 - test::run_test::run_test_inner::{{closure}}::h2693389a7e9432cd
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/test/src/lib.rs:489:39
  48:     0x56029148eec4 - test::run_test::run_test_inner::{{closure}}::hddde8315a809d5b2
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/test/src/lib.rs:516:37
  49:     0x56029148eec4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8c7d632389bdb829
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs:122:18
  50:     0x560291494817 - std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}::h956996300bf36fd9
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/mod.rs:514:17
  51:     0x560291494817 - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h15afb79792a96134
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs:271:9
  52:     0x560291494817 - std::panicking::try::do_call::h92147c5fcd629fe2
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:492:40
  53:     0x560291494817 - std::panicking::try::hbe2bdd2b47a3d39e
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:456:19
  54:     0x560291494817 - std::panic::catch_unwind::h8eb2b7b2b4bf9935
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs:137:14
  55:     0x560291494817 - std::thread::Builder::spawn_unchecked_::{{closure}}::hc48e77371cf4bd9e
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/mod.rs:513:30
  56:     0x560291494817 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h74dfdf4494a9b56e
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs:248:5
  57:     0x5602936bbec3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7d016ea8ca921d7f
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/alloc/src/boxed.rs:1940:9
  58:     0x5602936bbec3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf202f70e5b98a6cb
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/alloc/src/boxed.rs:1940:9
  59:     0x5602936bbec3 - std::sys::unix::thread::Thread::new::thread_start::hdc948a6935722a5a
                               at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys/unix/thread.rs:108:17
  60:     0x7f23eb535ea7 - start_thread
  61:     0x7f23eb2d2aef - clone
  62:                0x0 - <unknown>


failures:
    grpc::metasrv_grpc_kv_api::test_metasrv_kv_api

test result: FAILED. 50 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 56.36s

error: test failed, to rerun pass `-p databend-meta --test it`
     Running tests/it/main.rs (target/debug/deps/it-aa261fec977e9642)
```

**Comment by BohuTANG** [comment]
cc @drmingdrmer
