### ISSUE TITLE
bug: create default database report metaerror

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#8179]
### Search before asking

- [X] I had searched in the [issues](https://github.com/datafuselabs/databend/issues) and found no similar issues.

### Version

f05ef2edd0cb22e56cfe0d5e0cab417eb63f9270

### What's Wrong?

try to test databend with https://github.com/TCeason/test/tree/stream_load_test

use 100 CONCURRENCY , queue capacity 200 
```
     // nums of consumer thread
-    private static final int CONCURRENCY = 2;
-    private static final int QUEUE_CAPACITY = 10;
+    private static final int CONCURRENCY = 100;
+    private static final int QUEUE_CAPACITY = 200;
     private static  final byte[] DATA_END = new byte[0];
     // one queue mock rows nums
-    private static int MOCK_ROWS = 1000;
+    private static int MOCK_ROWS = 100000;
+    private static List<Object[]> rows = new ArrayList<>();
```

the databend return err and shutdown. I try to restart the query, it return err:

```
Error: Code: 2001, displayText = tokio::sync::oneshot::error::RecvError: channel closed while: when recv resp from MetaGrpcClient worker.

   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::MetaServiceError
             at /home/wu/wubx/fuse-query/src/common/exception/src/exception_code.rs:31:71
   1: common_meta_types::errors::meta_client_errors::<impl core::convert::From<common_meta_types::errors::meta_client_errors::MetaClientError> for common_exception::exception::ErrorCode>::from
             at /home/wu/wubx/fuse-query/src/meta/types/src/errors/meta_client_errors.rs:41:17
   2: <T as core::convert::Into<U>>::into
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/convert/mod.rs:552:9
   3: common_meta_types::errors::meta_errors::<impl core::convert::From<common_meta_types::errors::meta_errors::MetaError> for common_exception::exception::ErrorCode>::from
             at /home/wu/wubx/fuse-query/src/meta/types/src/errors/meta_errors.rs:49:43
   4: <T as core::convert::Into<U>>::into
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/convert/mod.rs:552:9
   5: common_meta_types::errors::kv_app_errors::<impl core::convert::From<common_meta_types::errors::kv_app_errors::KVAppError> for common_exception::exception::ErrorCode>::from
             at /home/wu/wubx/fuse-query/src/meta/types/src/errors/kv_app_errors.rs:54:48
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/result.rs:2105:27
   7: databend_query::catalogs::default::mutable_catalog::MutableCatalog::try_create_with_config::{{closure}}
             at /home/wu/wubx/fuse-query/src/query/service/src/catalogs/default/mutable_catalog.rs:115:9
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs:91:19
   9: databend_query::catalogs::default::database_catalog::DatabaseCatalog::try_create_with_config::{{closure}}
             at /home/wu/wubx/fuse-query/src/query/service/src/catalogs/default/database_catalog.rs:92:75
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs:91:19
  11: <common_catalog::catalog::CatalogManager as databend_query::catalogs::catalog_manager::CatalogManagerHelper>::register_build_in_catalogs::{{closure}}
             at /home/wu/wubx/fuse-query/src/query/service/src/catalogs/catalog_manager.rs:79:75
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs:91:19
  13: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/future.rs:124:9
  14: <common_catalog::catalog::CatalogManager as databend_query::catalogs::catalog_manager::CatalogManagerHelper>::try_create::{{closure}}
             at /home/wu/wubx/fuse-query/src/query/service/src/catalogs/catalog_manager.rs:67:57
  15: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs:91:19
  16: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/future.rs:124:9
  17: <common_catalog::catalog::CatalogManager as databend_query::catalogs::catalog_manager::CatalogManagerHelper>::init::{{closure}}
             at /home/wu/wubx/fuse-query/src/query/service/src/catalogs/catalog_manager.rs:49:38
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs:91:19
  19: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/future.rs:124:9
  20: databend_query::global_services::GlobalServices::init::{{closure}}
             at /home/wu/wubx/fuse-query/src/query/service/src/global_services.rs:81:63
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs:91:19
  22: databend_query::main::main_impl::{{closure}}
             at /home/wu/wubx/fuse-query/src/binaries/query/main.rs:76:39
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs:91:19
  24: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/future.rs:124:9
  25: futures_util::future::future::FutureExt::poll_unpin
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/futures-util-0.3.24/src/future/future/mod.rs:562:9
  26: <common_base::base::catch_unwind::CatchUnwindFuture<F> as core::future::future::Future>::poll::{{closure}}
             at /home/wu/wubx/fuse-query/src/common/base/src/base/catch_unwind.rs:54:36
  27: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs:271:9
  28: std::panicking::try::do_call
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:492:40
  29: std::panicking::try
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:456:19
  30: std::panic::catch_unwind
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs:137:14
  31: common_base::base::catch_unwind::catch_unwind
             at /home/wu/wubx/fuse-query/src/common/base/src/base/catch_unwind.rs:26:11
  32: <common_base::base::catch_unwind::CatchUnwindFuture<F> as core::future::future::Future>::poll
             at /home/wu/wubx/fuse-query/src/common/base/src/base/catch_unwind.rs:54:15
  33: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/park/thread.rs:267:54
  34: tokio::coop::with_budget::{{closure}}
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/coop.rs:102:9
  35: std::thread::local::LocalKey<T>::try_with
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/local.rs:445:16
  36: std::thread::local::LocalKey<T>::with
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/local.rs:421:9
  37: tokio::coop::with_budget
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/park/thread.rs:267:31
  38: tokio::coop::budget
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/coop.rs:72:5
  39: tokio::park::thread::CachedParkThread::block_on
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/park/thread.rs:267:31
  40: tokio::runtime::enter::Enter::block_on
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/enter.rs:152:13
  41: tokio::runtime::handle::Handle::block_on
             at /home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/handle.rs:301:9
  42: common_base::base::runtime::Runtime::block_on
             at /home/wu/wubx/fuse-query/src/common/base/src/base/runtime.rs:191:9
  43: databend_query::main
             at /home/wu/wubx/fuse-query/src/binaries/query/main.rs:231:7
  44: core::ops::function::FnOnce::call_once
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs:248:5
  45: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs:122:18
  46: std::rt::lang_start::{{closure}}
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/rt.rs:166:18
  47: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs:283:13
  48: std::panicking::try::do_call
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:492:40
  49: std::panicking::try
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:456:19
  50: std::panic::catch_unwind
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs:137:14
  51: std::rt::lang_start_internal::{{closure}}
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/rt.rs:148:48
  52: std::panicking::try::do_call
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:492:40
  53: std::panicking::try
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs:456:19
  54: std::panic::catch_unwind
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs:137:14
  55: std::rt::lang_start_internal
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/rt.rs:148:20
  56: main
  57: __libc_start_main
             at /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
  58: _start


```

Watch this :

```
   5: common_meta_types::errors::kv_app_errors::<impl core::convert::From<common_meta_types::errors::kv_app_errors::KVAppError> for common_exception::exception::ErrorCode>::from
             at /home/wu/wubx/fuse-query/src/meta/types/src/errors/kv_app_errors.rs:54:48
   6: <core::result::Result<T,F> as core::ops::try_trait::FromResidual<core::result::Result<core::convert::Infallible,E>>>::from_residual
             at /rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/result.rs:2105:27
   7: databend_query::catalogs::default::mutable_catalog::MutableCatalog::try_create_with_config::{{closure}}
             at /home/wu/wubx/fuse-query/src/query/service/src/catalogs/default/mutable_catalog.rs:115:9
```

![image](https://user-images.githubusercontent.com/33082201/195476027-b2c88b73-16b8-427d-ada5-2609875f38ab.png)

### How to Reproduce?

modify the java code and then run it.

```
mvn compile
mvn exec:java -Dexec.mainClass="org.example.Main"
```

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by TCeason** [comment]
before start, the server log has a panic info:

```
{
  "v": 0,
  "name": "databend-query-test_tenant-test_cluster",
  "msg": "panicked at 'Invalid semver: \"cannot describe - no reference found, cannot describe anything.; class=Describe (28)\": unexpected character 'c' while parsing major version number', src/meta/client/src/lib.rs:38:47",
  "level": 50,
  "hostname": "fz001.databend.cn",
  "pid": 3343030,
  "time": "2022-10-12T16:01:13.345512288Z",
  "target": "common_tracing::panic_hook",
  "line": 36,
  "file": "src/common/tracing/src/panic_hook.rs",
  "panic.column": 47,
  "panic.file": "src/meta/client/src/lib.rs",
  "panic.line": 38,
  "backtrace": "Backtrace [{ fn: \"common_tracing::panic_hook::log_panic\", file: \"/home/wu/wubx/fuse-query/src/common/tracing/src/panic_hook.rs\", line: 33 }, { fn: \"std::panicking::rust_panic_with_hook\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 702 }, { fn: \"std::panicking::begin_panic_handler::{{closure}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 588 }, { fn: \"std::sys_common::backtrace::__rust_end_short_backtrace\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs\", line: 138 }, { fn: \"rust_begin_unwind\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 584 }, { fn: \"core::panicking::panic_fmt\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panicking.rs\", line: 142 }, { fn: \"common_meta_client::METACLI_COMMIT_SEMVER::{{closure}}::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/lib.rs\", line: 38 }, { fn: \"core::result::Result<T,E>::unwrap_or_else\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/result.rs\", line: 1498 }, { fn: \"common_meta_client::METACLI_COMMIT_SEMVER::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/lib.rs\", line: 38 }, { fn: \"core::ops::function::FnOnce::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs\", line: 248 }, { fn: \"core::ops::function::FnOnce::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs\", line: 248 }, { fn: \"once_cell::sync::Lazy<T,F>::force::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/lib.rs\", line: 1260 }, { fn: \"once_cell::sync::OnceCell<T>::get_or_init::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/lib.rs\", line: 1072 }, { fn: \"once_cell::imp::OnceCell<T>::initialize::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/imp_std.rs\", line: 85 }, { fn: \"core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs\", line: 294 }, { fn: \"once_cell::imp::initialize_or_wait\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/imp_std.rs\", line: 216 }, { fn: \"once_cell::imp::OnceCell<T>::initialize\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/imp_std.rs\", line: 81 }, { fn: \"once_cell::sync::OnceCell<T>::get_or_try_init\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/lib.rs\", line: 1112 }, { fn: \"once_cell::sync::OnceCell<T>::get_or_init\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/lib.rs\", line: 1072 }, { fn: \"once_cell::sync::Lazy<T,F>::force\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/lib.rs\", line: 1259 }, { fn: \"<once_cell::sync::Lazy<T,F> as core::ops::deref::Deref>::deref\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/once_cell-1.15.0/src/lib.rs\", line: 1320 }, { fn: \"common_meta_client::grpc_client::MetaGrpcClient::make_client::{{closure}}::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/grpc_client.rs\", line: 478 }, { fn: \"<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs\", line: 91 }, { fn: \"common_meta_client::grpc_client::MetaGrpcClient::make_client::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/grpc_client.rs\", line: 456 }, { fn: \"<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs\", line: 91 }, { fn: \"common_meta_client::grpc_client::MetaGrpcClient::do_read::{{closure}}::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/grpc_client.rs\", line: 854 }, { fn: \"<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs\", line: 91 }, { fn: \"common_meta_client::grpc_client::MetaGrpcClient::do_read::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/grpc_client.rs\", line: 832 }, { fn: \"<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs\", line: 91 }, { fn: \"common_meta_client::grpc_client::MetaGrpcClient::worker_loop::{{closure}}::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/grpc_client.rs\", line: 355 }, { fn: \"<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs\", line: 91 }, { fn: \"common_meta_client::grpc_client::MetaGrpcClient::worker_loop::{{closure}}\", file: \"/home/wu/wubx/fuse-query/src/meta/client/src/grpc_client.rs\", line: 322 }, { fn: \"<core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/future/mod.rs\", line: 91 }, { fn: \"tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/core.rs\", line: 184 }, { fn: \"tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/loom/std/unsafe_cell.rs\", line: 14 }, { fn: \"tokio::runtime::task::core::CoreStage<T>::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/core.rs\", line: 174 }, { fn: \"tokio::runtime::task::harness::poll_future::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 480 }, { fn: \"<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs\", line: 271 }, { fn: \"std::panicking::try::do_call\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 492 }, { fn: \"std::panicking::try\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 456 }, { fn: \"std::panic::catch_unwind\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs\", line: 137 }, { fn: \"tokio::runtime::task::harness::poll_future\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 468 }, { fn: \"tokio::runtime::task::harness::Harness<T,S>::poll_inner\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 104 }, { fn: \"tokio::runtime::task::harness::Harness<T,S>::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 57 }, { fn: \"tokio::runtime::task::raw::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/raw.rs\", line: 194 }, { fn: \"tokio::runtime::task::raw::RawTask::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/raw.rs\", line: 134 }, { fn: \"tokio::runtime::task::LocalNotified<S>::run\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/mod.rs\", line: 385 }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs\", line: 444 }, { fn: \"tokio::coop::with_budget::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/coop.rs\", line: 102 }, { fn: \"std::thread::local::LocalKey<T>::try_with\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/local.rs\", line: 445 }, { fn: \"std::thread::local::LocalKey<T>::with\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/local.rs\", line: 421 }, { fn: \"tokio::coop::with_budget\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs\", line: 420 }, { fn: \"tokio::coop::budget\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/coop.rs\", line: 72 }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::Context::run_task\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs\", line: 420 }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::Context::run\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs\", line: 387 }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs\", line: 372 }, { fn: \"tokio::macros::scoped_tls::ScopedKey<T>::set\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/macros/scoped_tls.rs\", line: 61 }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::run\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs\", line: 369 }, { fn: \"tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/scheduler/multi_thread/worker.rs\", line: 348 }, { fn: \"<tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/blocking/task.rs\", line: 42 }, { fn: \"tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/core.rs\", line: 184 }, { fn: \"tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/loom/std/unsafe_cell.rs\", line: 14 }, { fn: \"tokio::runtime::task::core::CoreStage<T>::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/core.rs\", line: 174 }, { fn: \"tokio::runtime::task::harness::poll_future::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 480 }, { fn: \"<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs\", line: 271 }, { fn: \"std::panicking::try::do_call\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 492 }, { fn: \"std::panicking::try\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 456 }, { fn: \"std::panic::catch_unwind\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs\", line: 137 }, { fn: \"tokio::runtime::task::harness::poll_future\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 468 }, { fn: \"tokio::runtime::task::harness::Harness<T,S>::poll_inner\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 104 }, { fn: \"tokio::runtime::task::harness::Harness<T,S>::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/harness.rs\", line: 57 }, { fn: \"tokio::runtime::task::raw::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/raw.rs\", line: 194 }, { fn: \"tokio::runtime::task::raw::RawTask::poll\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/raw.rs\", line: 134 }, { fn: \"tokio::runtime::task::UnownedTask<S>::run\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/task/mod.rs\", line: 422 }, { fn: \"tokio::runtime::blocking::pool::Task::run\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/blocking/pool.rs\", line: 111 }, { fn: \"tokio::runtime::blocking::pool::Inner::run\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/blocking/pool.rs\", line: 346 }, { fn: \"tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}\", file: \"/home/wu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/tokio-1.21.1/src/runtime/blocking/pool.rs\", line: 321 }, { fn: \"std::sys_common::backtrace::__rust_begin_short_backtrace\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys_common/backtrace.rs\", line: 122 }, { fn: \"std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/mod.rs\", line: 514 }, { fn: \"<core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/panic/unwind_safe.rs\", line: 271 }, { fn: \"std::panicking::try::do_call\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 492 }, { fn: \"std::panicking::try\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panicking.rs\", line: 456 }, { fn: \"std::panic::catch_unwind\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/panic.rs\", line: 137 }, { fn: \"std::thread::Builder::spawn_unchecked_::{{closure}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/thread/mod.rs\", line: 513 }, { fn: \"core::ops::function::FnOnce::call_once{{vtable.shim}}\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/core/src/ops/function.rs\", line: 248 }, { fn: \"<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/alloc/src/boxed.rs\", line: 1940 }, { fn: \"<alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/alloc/src/boxed.rs\", line: 1940 }, { fn: \"std::sys::unix::thread::Thread::new::thread_start\", file: \"/rustc/98ad6a5519651af36e246c0335c964dd52c554ba/library/std/src/sys/unix/thread.rs\", line: 108 }, { fn: \"start_thread\", file: \"/build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c\", line: 477 }, { fn: \"clone\", file: \"/build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S\", line: 95 }]"
}
{"v":0,"name":"databend-query-test_tenant-test_cluster","msg":"common_meta_api::schema_api_impl","level":50,"hostname":"fz001.databend.cn","pid":3343030,"time":"2022-10-12T16:01:13.345690684Z","target":"common_meta_api::schema_api_impl","line":145,"file":"src/meta/api/src/schema_api_impl.rs","error":"fail to access meta-store: meta-client dedicated runtime error: tokio::sync::oneshot::error::RecvError: channel closed while: when recv resp from MetaGrpcClient worker"}

```

**Comment by TCeason** [comment]
what does panic mean?

  "msg": "panicked at 'Invalid semver: \"cannot describe - no reference found, cannot describe anything.; class=Describe (28)\": unexpected character 'c' while parsing major version number', src/meta/client/src/lib.rs:38:47",

**Comment by drmingdrmer** [comment]
Databend-query and databend-meta generate the version from their local git-tag, such as `v0.8.65-nightly`.

There will be a panic if the git tag is missing.

This is a known issue but has nothing to do with the concurrency issue. I believe these are two unrelated issues.

**Comment by Xuanwo** [comment]
The query used in this issue is incorrect. Let's close.
