### ISSUE TITLE
Feature: Support datax

### ISSUE THREAD

**Issue by TCeason** [datafuselabs/databend#8955]
**Summary**

```
  2022-11-24T11:15:39.226298Z  INFO databend_query::servers::http::middleware: receive http handler request: Request { method: POST, uri: /?user=u1&database=default&password=123&extremes=0&query_id=07e079cc-bcef-48dd-b800-82a65d92adac&compress=1, version: HTTP/1.1, headers: {"content-length": "55", "content-type": "text/plain; charset=UTF-8", "host": "127.0.0.1:8124", "connection": "Keep-Alive", "user-agent": "Apache-HttpClient/4.5.13 (Java/17.0.5)"} },
    at src/query/service/src/servers/http/middleware.rs:152

  2022-11-24T11:15:39.227055Z ERROR databend_query::servers::http::middleware: http request error: No authorization header detected
```

Now , if want to use clickhouse, need has auth with header "X-CLICKHOUSE-USER" and "X-CLICKHOUSE-KEY".

But datax send a uri like this: ` /?user=u1&database=default&password=123&extremes=0&query_id=07e079cc-bcef-48dd-b800-82a65d92adac&compress=1`

So it will return err: **No authorization header detected**

**Comment by TCeason** [comment]
cc @youngsofun  @wubx

**Comment by TCeason** [comment]
How about do like this : https://github.com/ClickHouse/ClickHouse/blob/4e76629aafc4e855e6a1d006e655d48ea141c6ea/src/Server/HTTPHandler.cpp#L403

**Comment by xudong963** [comment]
Do you mean [the project](https://github.com/alibaba/DataX)?

Currently, only support writer plugin should be enough.

**Comment by TCeason** [comment]
> Do you mean [the project](https://github.com/alibaba/DataX)?
> 
> Currently, only support writer plugin should be enough.

Yes. Now some user use this project to load data into databend.

**Comment by TCeason** [comment]
> Do you mean [the project](https://github.com/alibaba/DataX)?
> 
> Currently, only support writer plugin should be enough.

datax will return err :

```
com.alibaba.datax.common.exception.DataXException: Code:[DBUtilErrorCode-10], Description:[连接数据库失败. 请检查您的 账号、密码、数据库名称、IP、Port或者向 DBA 寻求帮助(注意网络环境).].  -  具体错误信息为：java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 210, host: 127.0.0.1, port: 8124; Connect to 127.0.0.1:8124 [/127.0.0.1] failed: 拒绝连接
	at com.alibaba.datax.common.exception.DataXException.asDataXException(DataXException.java:30)
	at com.alibaba.datax.plugin.rdbms.util.RdbmsException.asConnException(RdbmsException.java:36)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.connect(DBUtil.java:397)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.connect(DBUtil.java:387)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.access$000(DBUtil.java:22)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$3.call(DBUtil.java:322)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil$3.call(DBUtil.java:319)
	at com.alibaba.datax.common.util.RetryUtil$Retry.call(RetryUtil.java:164)
	at com.alibaba.datax.common.util.RetryUtil$Retry.doRetry(RetryUtil.java:111)
	at com.alibaba.datax.common.util.RetryUtil.executeWithRetry(RetryUtil.java:30)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getConnection(DBUtil.java:319)
	at com.alibaba.datax.plugin.rdbms.util.DBUtil.getConnection(DBUtil.java:303)
	at com.alibaba.datax.plugin.rdbms.util.JdbcConnectionFactory.getConnecttion(JdbcConnectionFactory.java:27)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:105)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.dealColumnConf(OriginalConfPretreatmentUtil.java:140)
	at com.alibaba.datax.plugin.rdbms.writer.util.OriginalConfPretreatmentUtil.doPretreatment(OriginalConfPretreatmentUtil.java:35)
	at com.alibaba.datax.plugin.rdbms.writer.CommonRdbmsWriter$Job.init(CommonRdbmsWriter.java:41)
	at com.alibaba.datax.plugin.writer.clickhousewriter.ClickhouseWriter$Job.init(ClickhouseWriter.java:36)
	at com.alibaba.datax.core.job.JobContainer.initJobWriter(JobContainer.java:704)
	at com.alibaba.datax.core.job.JobContainer.init(JobContainer.java:304)
	at com.alibaba.datax.core.job.JobContainer.start(JobContainer.java:113)
	at com.alibaba.datax.core.Engine.start(Engine.java:93)
	at com.alibaba.datax.core.Engine.entry(Engine.java:175)
	at com.alibaba.datax.core.Engine.main(Engine.java:208)

```

Because we need two head, but datax not support.

**Comment by youngsofun** [comment]
not only user/password, all the params used need support 


- database=default.   easy 
- extremes=0. easy if always 0
- user=u1&&password=123  not too hard

 not sure:

- compress=1 
- query_id=07e079cc-bcef-48dd-b800-82a65d92adac

**Comment by sundy-li** [comment]
So we can skip the useless head like federation.

**Comment by TCeason** [comment]
Priority L1 header
Priority L2 uri user, passed

**Comment by TCeason** [comment]
> not only user/password, all the params used need support
> 
> * database=default.   easy
> * extremes=0. easy if always 0
> * user=u1&&password=123  not too hard
> 
> not sure:
> 
> * compress=1
> * query_id=07e079cc-bcef-48dd-b800-82a65d92adac

I think we can skip the compression and query_id.

**Comment by youngsofun** [comment]
> So we can skip the useless head like federation.

cloud use the header for auth cc @ZhiHanZ @flaneur2020

**Comment by TCeason** [comment]
Test:

table in MySQL
```sql
create table db.exec(id varchar(20), col1 varchar(20));
insert into db.exec values('testfor', 'incol1');
```
table in Databend
```sql
CREATE TABLE `exec` (
  `id` VARCHAR NULL,
  `col1` VARCHAR NULL
)
```

I try to mock a user(u1) and password(123) to pass the auth in databend. 

But the sql that generate by datax is like this:

```sql
insert INTO exec (id)  FORMAT TabSeparatedtestfor
-- the `testfor` is the value of exec.id.
insert INTO exec (id,col1) VALUES('testfor','incol1')
```

So we from_str(tabseparatedtestfor) and then return err :

```
  2022-12-01T08:07:20.285117Z  INFO databend_query::servers::http::middleware: receive http handler request: Request { method: POST, uri: /?query=insert+INTO+exec+%28id%2Ccol1%29++FORMAT+TabSeparated&database=test&compress=1&password=123&user=u1, version: HTTP/1.1, headers: {"transfer-encoding": "chunked", "host": "127.0.0.1:8124", "connection": "Keep-Alive", "user-agent": "Apache-HttpClient/4.5.13 (Java/17.0.5)"} },
    at src/query/service/src/servers/http/middleware.rs:152

  2022-12-01T08:07:20.388960Z  INFO databend_query::servers::http::clickhouse_handler: receive clickhouse http post, (query + body) = insert INTO exec (id,col1)  FORMAT TabSeparatedtestfor	incol1

    at src/query/service/src/servers/http/clickhouse_handler.rs:251

  2022-12-01T08:07:20.426476Z ERROR databend_query::servers::http::middleware: http request error: Code: 1074, displayText = Unknown file format type 'tabseparatedtestfor', must be one of ( CSV | TSV | NDJSON | PARQUET | XML).
    at src/query/service/src/servers/http/middleware.rs:164

  2022-12-01T08:07:20.430375Z  INFO databend_query::servers::http::middleware: receive http handler request: Request { method: POST, uri: /?query_id=db07d53d-d719-4cf1-9795-5fb361b555a6&database=test&compress=1&password=123&user=u1&extremes=0, version: HTTP/1.1, headers: {"content-length": "53", "content-type": "text/plain; charset=UTF-8", "host": "127.0.0.1:8124", "connection": "Keep-Alive", "user-agent": "Apache-HttpClient/4.5.13 (Java/17.0.5)"} },
    at src/query/service/src/servers/http/middleware.rs:152

  2022-12-01T08:07:20.528052Z  INFO databend_query::servers::http::clickhouse_handler: receive clickhouse http post, (query + body) = insert INTO exec (id,col1) VALUES('testfor','incol1')
    at src/query/service/src/servers/http/clickhouse_handler.rs:251

```

I'm not sure how to deal with this: `insert INTO exec (id,col1)  FORMAT TabSeparatedtestfor	incol1`?

**Comment by sundy-li** [comment]
`TabSeparatedtestfor` is strange ...

**Comment by TCeason** [comment]
`insert INTO exec (id,col1) FORMAT TabSeparatedtestfor incol1`

The query maybe like this:

```sql
insert INTO exec (id,col1) FORMAT TabSeparated testfor incol1
```

**Comment by TCeason** [comment]
I got it. 

Datax use ck jdbc 0.2.4 , this version's jdbc not support X-CLICKHOUSE-KEY/USER. JDBC version that lastest support these headers is 0.3.1-patch. 

But we can't upgrade the datax's clickhousewirter jdbc version, because datax will try to execute [`doBatchInsert`](https://github.com/alibaba/DataX/blob/78384028492cca487f68e512f2f0079402ef5780/plugin-rdbms-util/src/main/java/com/alibaba/datax/plugin/rdbms/writer/CommonRdbmsWriter.java#L348) and clickhouse jdbc's will return when [setAutoCommit](https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.3.1-patch/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseConnectionImpl.java#L215) receive false param, will throw exception.

So if we want to support DataX accord ck jdbc, I think there is one way:

support parse this uri `/?user=u1&database=default&password=123&extremes=0&query_id=07e079cc-bcef-48dd-b800-82a65d92adac&compress=1` to get USER and PASSWORD.

Next, if want to support DataX batch insert into databend, we need resolve this:  

```
insert INTO exec (id)  FORMAT TabSeparatedtestfor
-- the `testfor` is the value of exec.id.
```

**Comment by youngsofun** [comment]
where is the code that lead to `TabSeparatedtestfor`? 
I think it it is reasonable to patch it: add space or `\n` after `TabSeparated`.

seems not in [datax](https://github.com/alibaba/DataX/blob/master/clickhousewriter/src/main/java/com/alibaba/datax/plugin/writer/clickhousewriter/ClickhouseWriter.java)

**Comment by TCeason** [comment]
> where is the code that lead to `TabSeparatedtestfor`? I think it it is reasonable to patch it: add space or `\n` after `TabSeparated`.
> 
> seems not in [datax](https://github.com/alibaba/DataX/blob/master/clickhousewriter/src/main/java/com/alibaba/datax/plugin/writer/clickhousewriter/ClickhouseWriter.java)

I haven’t see this. But I think we can support user first. The next step is this.

**Comment by sundy-li** [comment]
```
    let mut sql = params.query();
    sql.push_str(body.into_string().await?.as_str());
```

we need a space to concat the SQL string.

**Comment by TCeason** [comment]
Thanks for @wubx  providing an alternative approach. We can use the MySQL protocol to synchronize data. I have locally tested that the string type can be synchronized. And databend query does not have err.  Based on the [research here](https://github.com/datafuselabs/databend/issues/8955#issuecomment-1333514914), I think we can close out this issue

```sql
-- table in MySQL

CREATE TABLE db.`exec` (
  `id` varchar(20) DEFAULT NULL,
  `col1` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1

-- table in Databend

CREATE TABLE test.`exec` (
  `id` VARCHAR NULL,
  `col1` VARCHAR NULL
) ENGINE=FUSE SNAPSHOT_LOCATION='8641/8647/_ss/988aeb7eb261415e813ef54ae88b56e5_v1.json'

```
datax json like this:

```json
{
	"job": {
		"content": [{
			"reader": {
				"name": "mysqlreader",
				"parameter": {
					"column": [
						"id","col1"
					],
					"connection": [{
						"jdbcUrl": ["jdbc:mysql://127.0.0.1:3306/db?useUnicode=true&characterEncoding=utf-8&useSSL=false"],
						"table": [
							"exec"
						]
					}],
					"password": "123",
					"username": "mysqlu1",
					"where": ""
				}
			},
			"writer": {
				"name": "mysqlwriter",
				"parameter": {
					"batchByteSize": 134217728,
					"batchSize": 65536,
					"column": [
						"id", "col1"
					],
					"connection": [{
						"jdbcUrl": "jdbc:mysql://127.0.0.1:3307/test?useUnicode=true&characterEncoding=utf-8&useSSL=false",
						"table": [
							"exec"
						]
					}],
					"dryRun": false,
					"password": "123",
					"postSql": [],
					"preSql": [],
					"username": "u1",
					"writeMode": "insert"
				}
			}
		}],
		"setting": {
			"speed": {
				"channel": "5"
			}
		}
	}
}

```
