### ISSUE TITLE
bug: delete from d2 where id in (select id from d1) panic

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/databend#9849]
**Summary**

```
mysql> create table d2(id int);
Query OK, 0 rows affected (0.11 sec)

mysql> insert into d1 values(1),(2);
Query OK, 2 rows affected (0.15 sec)

mysql> insert into d2 values(1),(2),(3),(4);
Query OK, 4 rows affected (0.11 sec)

mysql> delete from d2 where id in (select id from d1);
ERROR 1105 (HY000): Code: 1068, displayText = Cannot join handle from context's runtime, cause: task 867229 panicked.
```

server log:
```
try/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/harness.rs", line: 198 }, { fn: ""tokio"::"runtime"::"task"::"harness"::"Harness<T",
"S>"::"poll"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/harness.rs", line: 152 }, { fn: ""tokio"::"runtime"::"task"::"raw"::"RawTask"::"poll"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/raw.rs", line: 200 }, { fn: ""tokio"::"runtime"::"task"::"LocalNotified<S>"::"run"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/mod.rs", line: 459 }, { fn: ""tokio"::"runtime"::"scheduler"::"multi_thread"::"worker"::"Context"::"run_task"::{
   {
      "closure"
   }
}", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs", line: 464 }, { fn: ""tokio"::"runtime"::"coop"::"with_budget"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/coop.rs", line: 102 }, { fn: ""tokio"::"runtime"::"coop"::"budget"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/coop.rs", line: 68 }, { fn: ""tokio"::"runtime"::"scheduler"::"multi_thread"::"worker"::"Context"::"run_task"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs", line: 463 }, { fn: ""tokio"::"runtime"::"scheduler"::"multi_thread"::"worker"::"Context"::"run"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs", line: 426 }, { fn: ""tokio"::"runtime"::"scheduler"::"multi_thread"::"worker"::"run"::{
   {
      "closure"
   }
}", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs", line: 406 }, { fn: ""tokio"::"macros"::"scoped_tls"::"ScopedKey<T>"::"set"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/macros/scoped_tls.rs", line: 61 }, { fn: ""tokio"::"runtime"::"scheduler"::"multi_thread"::"worker"::"run"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs", line: 403 }, { fn: ""tokio"::"runtime"::"scheduler"::"multi_thread"::"worker"::"Launch"::"launch"::{
   {
      "closure"
   }
}", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/scheduler/multi_thread/worker.rs", line: 365 }, { fn: ""<tokio"::"runtime"::"blocking"::"task"::"BlockingTask<T> as core"::"future"::"future"::"Future>"::"poll"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/blocking/task.rs", line: 42 }, { fn: ""tokio"::"runtime"::"task"::"core"::"Core<T",
"S>"::"poll"::{
   {
      "closure"
   }
}", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/core.rs", line: 223 }, { fn: ""tokio"::"loom"::"std"::"unsafe_cell"::"UnsafeCell<T>"::"with_mut"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/loom/std/unsafe_cell.rs", line: 14 }, { fn: ""tokio"::"runtime"::"task"::"core"::"Core<T",
"S>"::"poll"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/core.rs", line: 212 }, { fn: ""tokio"::"runtime"::"task"::"harness"::"poll_future"::{
   {
      "closure"
   }
}", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/harness.rs", line: 481 }, { fn: ""<core"::"panic"::"unwind_safe"::"AssertUnwindSafe<F> as core"::"ops"::"function"::"FnOnce<()>>"::"call_once"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: ""std"::"panicking"::"try"::"do_call"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 483 }, { fn: ""std"::"panicking"::"try"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 447 }, { fn: ""std"::"panic"::"catch_unwind"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panic.rs", line: 137 }, { fn: ""tokio"::"runtime"::"task"::"harness"::"poll_future"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/harness.rs", line: 469 }, { fn: ""tokio"::"runtime"::"task"::"harness"::"Harness<T",
"S>"::"poll_inner"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/harness.rs", line: 198 }, { fn: ""tokio"::"runtime"::"task"::"harness"::"Harness<T",
"S>"::"poll"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/harness.rs", line: 152 }, { fn: ""tokio"::"runtime"::"task"::"raw"::"poll"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/raw.rs", line: 255 }, { fn: ""tokio"::"runtime"::"task"::"raw"::"RawTask"::"poll"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/raw.rs", line: 200 }, { fn: ""tokio"::"runtime"::"task"::"UnownedTask<S>"::"run"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/task/mod.rs", line: 496 }, { fn: ""tokio"::"runtime"::"blocking"::"pool"::"Task"::"run"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/blocking/pool.rs", line: 159 }, { fn: ""tokio"::"runtime"::"blocking"::"pool"::"Inner"::"run"", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/blocking/pool.rs", line: 510 }, { fn: ""tokio"::"runtime"::"blocking"::"pool"::"Spawner"::"spawn_thread"::{
   {
      "closure"
   }
}", file: "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.23.1/src/runtime/blocking/pool.rs", line: 468 }, { fn: ""std"::"sys_common"::"backtrace"::"__rust_begin_short_backtrace"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys_common/backtrace.rs", line: 121 }, { fn: ""std"::"thread"::"Builder"::"spawn_unchecked_"::{
   {
      "closure"
   }
}::{
   {
      "closure"
   }
}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/thread/mod.rs", line: 550 }, { fn: ""<core"::"panic"::"unwind_safe"::"AssertUnwindSafe<F> as core"::"ops"::"function"::"FnOnce<()>>"::"call_once"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/panic/unwind_safe.rs", line: 271 }, { fn: ""std"::"panicking"::"try"::"do_call"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 483 }, { fn: ""std"::"panicking"::"try"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panicking.rs", line: 447 }, { fn: ""std"::"panic"::"catch_unwind"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/panic.rs", line: 137 }, { fn: ""std"::"thread"::"Builder"::"spawn_unchecked_"::{
   {
      "closure"
   }
}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/thread/mod.rs", line: 549 }, { fn: ""core"::"ops"::"function"::"FnOnce"::"call_once"{
   {
      "vtable.shim"
   }
}", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/core/src/ops/function.rs", line: 507 }, { fn: ""<alloc"::"boxed"::"Box<F",
"A> as core"::"ops"::"function"::"FnOnce<Args>>"::"call_once"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs", line: 2000 }, { fn: ""<alloc"::"boxed"::"Box<F",
"A> as core"::"ops"::"function"::"FnOnce<Args>>"::"call_once"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/alloc/src/boxed.rs", line: 2000 }, { fn: ""std"::"sys"::"unix"::"thread"::"Thread"::"new"::"thread_start"", file: "/rustc/b70baa4f922a1809d79caeaeb902800c3be283b9/library/std/src/sys/unix/thread.rs", line: 108 }, { fn: ""start_thread"", file: ""./nptl/./nptl/pthread_create.c"", line: 442 }, { fn: "clone3", file: "./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S", line: 81 }], panic.file: ""src/query/storages/fuse/src/operations/delete.rs""\", panic.line: 169, panic.column: 62
    at src/common/tracing/src/panic_hook.rs:38"
```

```
{ fn: "clone3", file: "./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S", line: 81 }], panic.file: "src/query/storages/fuse/src/operations/delete.rs", panic.line: 169, panic.column: 62
```

**Comment by sundy-li** [comment]
```
ERROR common_tracing::panic_hook: panicked at 'called `Result::unwrap()` on an `Err` value: Code: 1006, displayText = Unable to get field named "DUMMY". V
alid fields: ["id"].

   0: common_exception::exception_code::<impl common_exception::exception::ErrorCode>::BadArguments
             at ./src/common/exception/src/exception_code.rs:38:71                                                                                                                         1: common_expression::schema::TableSchema::index_of
             at ./src/query/expression/src/schema.rs:471:13
   2: common_storages_fuse::operations::delete::<impl common_storages_fuse::fuse_table::FuseTable>::try_eval_const::{{closure}}
             at ./src/query/storages/fuse/src/operations/delete.rs:169:40                                                                                                                  3: project_column_ref<alloc::string::String, usize, common_storages_fuse::operations::delete::{impl#0}::try_eval_const::{closure_env#0}>
             at ./src/query/expression/src/expression.rs:332:21
   4: common_storages_fuse::operations::delete::<impl common_storages_fuse::fuse_table::FuseTable>::try_eval_const
             at ./src/query/storages/fuse/src/operations/delete.rs:167:27
   5: {async_fn#0}
             at ./src/query/storages/fuse/src/operations/delete.rs:113:16
   6: {async_block#0}
             at ./src/query/storages/fuse/src/fuse_table.rs:562:59
```

**Comment by sundy-li** [comment]
```
 ScalarExpr::SubqueryExpr(subquery) => RawExpr::ColumnRef {
                span: None,
                id: DUMMY_NAME.to_string(),
                data_type: subquery.data_type(),
                display_name: DUMMY_NAME.to_string(),
            },
```

**Comment by leiysky** [comment]
We haven't supported using subqueries in `DELETE` statement yet.

I've just opened an issue for this #9852.

**Comment by BohuTANG** [comment]
OK, we should return an unsupported error instead panic.
